// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             (unknown)
// source: search/v1/search.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationSearchSearchVideos = "/api.search.v1.Search/SearchVideos"
const OperationSearchSuggest = "/api.search.v1.Search/Suggest"

type SearchHTTPServer interface {
	// SearchVideos 标题/简介检索,仅返回 status=ready 稿件
	SearchVideos(context.Context, *SearchVideosRequest) (*SearchVideosReply, error)
	// Suggest 搜索框联想:标题前缀/子串,最多 10 条
	Suggest(context.Context, *SuggestRequest) (*SuggestReply, error)
}

func RegisterSearchHTTPServer(s *http.Server, srv SearchHTTPServer) {
	r := s.Route("/")
	r.GET("/v1/search/videos", _Search_SearchVideos0_HTTP_Handler(srv))
	r.GET("/v1/search/suggest", _Search_Suggest0_HTTP_Handler(srv))
}

func _Search_SearchVideos0_HTTP_Handler(srv SearchHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SearchVideosRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSearchSearchVideos)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SearchVideos(ctx, req.(*SearchVideosRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SearchVideosReply)
		return ctx.Result(200, reply)
	}
}

func _Search_Suggest0_HTTP_Handler(srv SearchHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SuggestRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSearchSuggest)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Suggest(ctx, req.(*SuggestRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SuggestReply)
		return ctx.Result(200, reply)
	}
}

type SearchHTTPClient interface {
	// SearchVideos 标题/简介检索,仅返回 status=ready 稿件
	SearchVideos(ctx context.Context, req *SearchVideosRequest, opts ...http.CallOption) (rsp *SearchVideosReply, err error)
	// Suggest 搜索框联想:标题前缀/子串,最多 10 条
	Suggest(ctx context.Context, req *SuggestRequest, opts ...http.CallOption) (rsp *SuggestReply, err error)
}

type SearchHTTPClientImpl struct {
	cc *http.Client
}

func NewSearchHTTPClient(client *http.Client) SearchHTTPClient {
	return &SearchHTTPClientImpl{client}
}

// SearchVideos 标题/简介检索,仅返回 status=ready 稿件
func (c *SearchHTTPClientImpl) SearchVideos(ctx context.Context, in *SearchVideosRequest, opts ...http.CallOption) (*SearchVideosReply, error) {
	var out SearchVideosReply
	pattern := "/v1/search/videos"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationSearchSearchVideos))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// Suggest 搜索框联想:标题前缀/子串,最多 10 条
func (c *SearchHTTPClientImpl) Suggest(ctx context.Context, in *SuggestRequest, opts ...http.CallOption) (*SuggestReply, error) {
	var out SuggestReply
	pattern := "/v1/search/suggest"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationSearchSuggest))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
