// X-Plore 搜索服务契约。
// V2 实现:PG ILIKE 读旁路(共库只读 videos 表);演进位:ES + outbox 同步,接口不变。

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: search/v1/search.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SearchVideosRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Q             string                 `protobuf:"bytes,1,opt,name=q,proto3" json:"q,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Size          int32                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Category      string                 `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"` // 可选分区过滤
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchVideosRequest) Reset() {
	*x = SearchVideosRequest{}
	mi := &file_search_v1_search_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchVideosRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchVideosRequest) ProtoMessage() {}

func (x *SearchVideosRequest) ProtoReflect() protoreflect.Message {
	mi := &file_search_v1_search_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchVideosRequest.ProtoReflect.Descriptor instead.
func (*SearchVideosRequest) Descriptor() ([]byte, []int) {
	return file_search_v1_search_proto_rawDescGZIP(), []int{0}
}

func (x *SearchVideosRequest) GetQ() string {
	if x != nil {
		return x.Q
	}
	return ""
}

func (x *SearchVideosRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *SearchVideosRequest) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *SearchVideosRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

type SearchHit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Category      string                 `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`
	UserId        uint64                 `protobuf:"varint,5,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Author        string                 `protobuf:"bytes,6,opt,name=author,proto3" json:"author,omitempty"`
	DurationSec   float64                `protobuf:"fixed64,7,opt,name=duration_sec,json=durationSec,proto3" json:"duration_sec,omitempty"`
	PlayCount     int64                  `protobuf:"varint,8,opt,name=play_count,json=playCount,proto3" json:"play_count,omitempty"`
	CoverUrl      string                 `protobuf:"bytes,9,opt,name=cover_url,json=coverUrl,proto3" json:"cover_url,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // unix ms
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchHit) Reset() {
	*x = SearchHit{}
	mi := &file_search_v1_search_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchHit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchHit) ProtoMessage() {}

func (x *SearchHit) ProtoReflect() protoreflect.Message {
	mi := &file_search_v1_search_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchHit.ProtoReflect.Descriptor instead.
func (*SearchHit) Descriptor() ([]byte, []int) {
	return file_search_v1_search_proto_rawDescGZIP(), []int{1}
}

func (x *SearchHit) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SearchHit) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *SearchHit) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *SearchHit) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *SearchHit) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SearchHit) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *SearchHit) GetDurationSec() float64 {
	if x != nil {
		return x.DurationSec
	}
	return 0
}

func (x *SearchHit) GetPlayCount() int64 {
	if x != nil {
		return x.PlayCount
	}
	return 0
}

func (x *SearchHit) GetCoverUrl() string {
	if x != nil {
		return x.CoverUrl
	}
	return ""
}

func (x *SearchHit) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type SearchVideosReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*SearchHit           `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchVideosReply) Reset() {
	*x = SearchVideosReply{}
	mi := &file_search_v1_search_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchVideosReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchVideosReply) ProtoMessage() {}

func (x *SearchVideosReply) ProtoReflect() protoreflect.Message {
	mi := &file_search_v1_search_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchVideosReply.ProtoReflect.Descriptor instead.
func (*SearchVideosReply) Descriptor() ([]byte, []int) {
	return file_search_v1_search_proto_rawDescGZIP(), []int{2}
}

func (x *SearchVideosReply) GetList() []*SearchHit {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *SearchVideosReply) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type SuggestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Q             string                 `protobuf:"bytes,1,opt,name=q,proto3" json:"q,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SuggestRequest) Reset() {
	*x = SuggestRequest{}
	mi := &file_search_v1_search_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SuggestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuggestRequest) ProtoMessage() {}

func (x *SuggestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_search_v1_search_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuggestRequest.ProtoReflect.Descriptor instead.
func (*SuggestRequest) Descriptor() ([]byte, []int) {
	return file_search_v1_search_proto_rawDescGZIP(), []int{3}
}

func (x *SuggestRequest) GetQ() string {
	if x != nil {
		return x.Q
	}
	return ""
}

type SuggestReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []string               `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SuggestReply) Reset() {
	*x = SuggestReply{}
	mi := &file_search_v1_search_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SuggestReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuggestReply) ProtoMessage() {}

func (x *SuggestReply) ProtoReflect() protoreflect.Message {
	mi := &file_search_v1_search_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuggestReply.ProtoReflect.Descriptor instead.
func (*SuggestReply) Descriptor() ([]byte, []int) {
	return file_search_v1_search_proto_rawDescGZIP(), []int{4}
}

func (x *SuggestReply) GetList() []string {
	if x != nil {
		return x.List
	}
	return nil
}

var File_search_v1_search_proto protoreflect.FileDescriptor

const file_search_v1_search_proto_rawDesc = "" +
	"\n" +
	"\x16search/v1/search.proto\x12\rapi.search.v1\x1a\x1cgoogle/api/annotations.proto\"g\n" +
	"\x13SearchVideosRequest\x12\f\n" +
	"\x01q\x18\x01 \x01(\tR\x01q\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x05R\x04size\x12\x1a\n" +
	"\bcategory\x18\x04 \x01(\tR\bcategory\"\x9e\x02\n" +
	"\tSearchHit\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1a\n" +
	"\bcategory\x18\x04 \x01(\tR\bcategory\x12\x17\n" +
	"\auser_id\x18\x05 \x01(\x04R\x06userId\x12\x16\n" +
	"\x06author\x18\x06 \x01(\tR\x06author\x12!\n" +
	"\fduration_sec\x18\a \x01(\x01R\vdurationSec\x12\x1d\n" +
	"\n" +
	"play_count\x18\b \x01(\x03R\tplayCount\x12\x1b\n" +
	"\tcover_url\x18\t \x01(\tR\bcoverUrl\x12\x1d\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\x03R\tcreatedAt\"W\n" +
	"\x11SearchVideosReply\x12,\n" +
	"\x04list\x18\x01 \x03(\v2\x18.api.search.v1.SearchHitR\x04list\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"\x1e\n" +
	"\x0eSuggestRequest\x12\f\n" +
	"\x01q\x18\x01 \x01(\tR\x01q\"\"\n" +
	"\fSuggestReply\x12\x12\n" +
	"\x04list\x18\x01 \x03(\tR\x04list2\xdc\x01\n" +
	"\x06Search\x12o\n" +
	"\fSearchVideos\x12\".api.search.v1.SearchVideosRequest\x1a .api.search.v1.SearchVideosReply\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/v1/search/videos\x12a\n" +
	"\aSuggest\x12\x1d.api.search.v1.SuggestRequest\x1a\x1b.api.search.v1.SuggestReply\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/v1/search/suggestB6Z4github.com/YansIlinta/wavehub-micro/api/search/v1;v1b\x06proto3"

var (
	file_search_v1_search_proto_rawDescOnce sync.Once
	file_search_v1_search_proto_rawDescData []byte
)

func file_search_v1_search_proto_rawDescGZIP() []byte {
	file_search_v1_search_proto_rawDescOnce.Do(func() {
		file_search_v1_search_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_search_v1_search_proto_rawDesc), len(file_search_v1_search_proto_rawDesc)))
	})
	return file_search_v1_search_proto_rawDescData
}

var file_search_v1_search_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_search_v1_search_proto_goTypes = []any{
	(*SearchVideosRequest)(nil), // 0: api.search.v1.SearchVideosRequest
	(*SearchHit)(nil),           // 1: api.search.v1.SearchHit
	(*SearchVideosReply)(nil),   // 2: api.search.v1.SearchVideosReply
	(*SuggestRequest)(nil),      // 3: api.search.v1.SuggestRequest
	(*SuggestReply)(nil),        // 4: api.search.v1.SuggestReply
}
var file_search_v1_search_proto_depIdxs = []int32{
	1, // 0: api.search.v1.SearchVideosReply.list:type_name -> api.search.v1.SearchHit
	0, // 1: api.search.v1.Search.SearchVideos:input_type -> api.search.v1.SearchVideosRequest
	3, // 2: api.search.v1.Search.Suggest:input_type -> api.search.v1.SuggestRequest
	2, // 3: api.search.v1.Search.SearchVideos:output_type -> api.search.v1.SearchVideosReply
	4, // 4: api.search.v1.Search.Suggest:output_type -> api.search.v1.SuggestReply
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_search_v1_search_proto_init() }
func file_search_v1_search_proto_init() {
	if File_search_v1_search_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_search_v1_search_proto_rawDesc), len(file_search_v1_search_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_search_v1_search_proto_goTypes,
		DependencyIndexes: file_search_v1_search_proto_depIdxs,
		MessageInfos:      file_search_v1_search_proto_msgTypes,
	}.Build()
	File_search_v1_search_proto = out.File
	file_search_v1_search_proto_goTypes = nil
	file_search_v1_search_proto_depIdxs = nil
}
