// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.3
// source: api/track/v1/track.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateTrackRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTrackRequest) Reset() {
	*x = CreateTrackRequest{}
	mi := &file_api_track_v1_track_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTrackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTrackRequest) ProtoMessage() {}

func (x *CreateTrackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_track_v1_track_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTrackRequest.ProtoReflect.Descriptor instead.
func (*CreateTrackRequest) Descriptor() ([]byte, []int) {
	return file_api_track_v1_track_proto_rawDescGZIP(), []int{0}
}

func (x *CreateTrackRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type CreateTrackReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UploadUrl     string                 `protobuf:"bytes,2,opt,name=upload_url,json=uploadUrl,proto3" json:"upload_url,omitempty"` // MinIO 预签名直传 URL：客户端拿它直接 PUT 音频，流量不经过本服务
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTrackReply) Reset() {
	*x = CreateTrackReply{}
	mi := &file_api_track_v1_track_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTrackReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTrackReply) ProtoMessage() {}

func (x *CreateTrackReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_track_v1_track_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTrackReply.ProtoReflect.Descriptor instead.
func (*CreateTrackReply) Descriptor() ([]byte, []int) {
	return file_api_track_v1_track_proto_rawDescGZIP(), []int{1}
}

func (x *CreateTrackReply) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CreateTrackReply) GetUploadUrl() string {
	if x != nil {
		return x.UploadUrl
	}
	return ""
}

type CompleteUploadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteUploadRequest) Reset() {
	*x = CompleteUploadRequest{}
	mi := &file_api_track_v1_track_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteUploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteUploadRequest) ProtoMessage() {}

func (x *CompleteUploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_track_v1_track_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteUploadRequest.ProtoReflect.Descriptor instead.
func (*CompleteUploadRequest) Descriptor() ([]byte, []int) {
	return file_api_track_v1_track_proto_rawDescGZIP(), []int{2}
}

func (x *CompleteUploadRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type CompleteUploadReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteUploadReply) Reset() {
	*x = CompleteUploadReply{}
	mi := &file_api_track_v1_track_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteUploadReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteUploadReply) ProtoMessage() {}

func (x *CompleteUploadReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_track_v1_track_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteUploadReply.ProtoReflect.Descriptor instead.
func (*CompleteUploadReply) Descriptor() ([]byte, []int) {
	return file_api_track_v1_track_proto_rawDescGZIP(), []int{3}
}

func (x *CompleteUploadReply) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ListTracksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Size          int32                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTracksRequest) Reset() {
	*x = ListTracksRequest{}
	mi := &file_api_track_v1_track_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTracksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTracksRequest) ProtoMessage() {}

func (x *ListTracksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_track_v1_track_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTracksRequest.ProtoReflect.Descriptor instead.
func (*ListTracksRequest) Descriptor() ([]byte, []int) {
	return file_api_track_v1_track_proto_rawDescGZIP(), []int{4}
}

func (x *ListTracksRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListTracksRequest) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type TrackInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	UserId        uint64                 `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Author        string                 `protobuf:"bytes,4,opt,name=author,proto3" json:"author,omitempty"` // 来自 user 服务的 gRPC 调用，不是本地 JOIN
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	DurationSec   float64                `protobuf:"fixed64,6,opt,name=duration_sec,json=durationSec,proto3" json:"duration_sec,omitempty"`
	PlayCount     int64                  `protobuf:"varint,7,opt,name=play_count,json=playCount,proto3" json:"play_count,omitempty"`
	Peaks         []float32              `protobuf:"fixed32,8,rep,packed,name=peaks,proto3" json:"peaks,omitempty"`                 // 波形峰值，详情页才返回
	StreamUrl     string                 `protobuf:"bytes,9,opt,name=stream_url,json=streamUrl,proto3" json:"stream_url,omitempty"` // 预签名播放地址(1小时有效)，status=ready 后才有
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrackInfo) Reset() {
	*x = TrackInfo{}
	mi := &file_api_track_v1_track_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrackInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackInfo) ProtoMessage() {}

func (x *TrackInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_track_v1_track_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackInfo.ProtoReflect.Descriptor instead.
func (*TrackInfo) Descriptor() ([]byte, []int) {
	return file_api_track_v1_track_proto_rawDescGZIP(), []int{5}
}

func (x *TrackInfo) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TrackInfo) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *TrackInfo) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *TrackInfo) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *TrackInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *TrackInfo) GetDurationSec() float64 {
	if x != nil {
		return x.DurationSec
	}
	return 0
}

func (x *TrackInfo) GetPlayCount() int64 {
	if x != nil {
		return x.PlayCount
	}
	return 0
}

func (x *TrackInfo) GetPeaks() []float32 {
	if x != nil {
		return x.Peaks
	}
	return nil
}

func (x *TrackInfo) GetStreamUrl() string {
	if x != nil {
		return x.StreamUrl
	}
	return ""
}

type ListTracksReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*TrackInfo           `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTracksReply) Reset() {
	*x = ListTracksReply{}
	mi := &file_api_track_v1_track_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTracksReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTracksReply) ProtoMessage() {}

func (x *ListTracksReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_track_v1_track_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTracksReply.ProtoReflect.Descriptor instead.
func (*ListTracksReply) Descriptor() ([]byte, []int) {
	return file_api_track_v1_track_proto_rawDescGZIP(), []int{6}
}

func (x *ListTracksReply) GetList() []*TrackInfo {
	if x != nil {
		return x.List
	}
	return nil
}

type GetTrackRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTrackRequest) Reset() {
	*x = GetTrackRequest{}
	mi := &file_api_track_v1_track_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTrackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTrackRequest) ProtoMessage() {}

func (x *GetTrackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_track_v1_track_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTrackRequest.ProtoReflect.Descriptor instead.
func (*GetTrackRequest) Descriptor() ([]byte, []int) {
	return file_api_track_v1_track_proto_rawDescGZIP(), []int{7}
}

func (x *GetTrackRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ReportProcessedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	DurationSec   float64                `protobuf:"fixed64,3,opt,name=duration_sec,json=durationSec,proto3" json:"duration_sec,omitempty"`
	Peaks         []float32              `protobuf:"fixed32,4,rep,packed,name=peaks,proto3" json:"peaks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportProcessedRequest) Reset() {
	*x = ReportProcessedRequest{}
	mi := &file_api_track_v1_track_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportProcessedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportProcessedRequest) ProtoMessage() {}

func (x *ReportProcessedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_track_v1_track_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportProcessedRequest.ProtoReflect.Descriptor instead.
func (*ReportProcessedRequest) Descriptor() ([]byte, []int) {
	return file_api_track_v1_track_proto_rawDescGZIP(), []int{8}
}

func (x *ReportProcessedRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ReportProcessedRequest) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ReportProcessedRequest) GetDurationSec() float64 {
	if x != nil {
		return x.DurationSec
	}
	return 0
}

func (x *ReportProcessedRequest) GetPeaks() []float32 {
	if x != nil {
		return x.Peaks
	}
	return nil
}

type ReportProcessedReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportProcessedReply) Reset() {
	*x = ReportProcessedReply{}
	mi := &file_api_track_v1_track_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportProcessedReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportProcessedReply) ProtoMessage() {}

func (x *ReportProcessedReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_track_v1_track_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportProcessedReply.ProtoReflect.Descriptor instead.
func (*ReportProcessedReply) Descriptor() ([]byte, []int) {
	return file_api_track_v1_track_proto_rawDescGZIP(), []int{9}
}

var File_api_track_v1_track_proto protoreflect.FileDescriptor

const file_api_track_v1_track_proto_rawDesc = "" +
	"\n" +
	"\x18api/track/v1/track.proto\x12\fapi.track.v1\x1a\x1cgoogle/api/annotations.proto\"*\n" +
	"\x12CreateTrackRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\"A\n" +
	"\x10CreateTrackReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x1d\n" +
	"\n" +
	"upload_url\x18\x02 \x01(\tR\tuploadUrl\"9\n" +
	"\x15CompleteUploadRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02idJ\x04\b\x02\x10\x03R\n" +
	"object_key\"-\n" +
	"\x13CompleteUploadReply\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\";\n" +
	"\x11ListTracksRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x05R\x04size\"\xf1\x01\n" +
	"\tTrackInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x04R\x06userId\x12\x16\n" +
	"\x06author\x18\x04 \x01(\tR\x06author\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12!\n" +
	"\fduration_sec\x18\x06 \x01(\x01R\vdurationSec\x12\x1d\n" +
	"\n" +
	"play_count\x18\a \x01(\x03R\tplayCount\x12\x14\n" +
	"\x05peaks\x18\b \x03(\x02R\x05peaks\x12\x1d\n" +
	"\n" +
	"stream_url\x18\t \x01(\tR\tstreamUrl\">\n" +
	"\x0fListTracksReply\x12+\n" +
	"\x04list\x18\x01 \x03(\v2\x17.api.track.v1.TrackInfoR\x04list\"!\n" +
	"\x0fGetTrackRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"{\n" +
	"\x16ReportProcessedRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12!\n" +
	"\fduration_sec\x18\x03 \x01(\x01R\vdurationSec\x12\x14\n" +
	"\x05peaks\x18\x04 \x03(\x02R\x05peaks\"\x16\n" +
	"\x14ReportProcessedReply2\x8a\x04\n" +
	"\x05Track\x12f\n" +
	"\vCreateTrack\x12 .api.track.v1.CreateTrackRequest\x1a\x1e.api.track.v1.CreateTrackReply\"\x15\x82\xd3\xe4\x93\x02\x0f:\x01*\"\n" +
	"/v1/tracks\x12}\n" +
	"\x0eCompleteUpload\x12#.api.track.v1.CompleteUploadRequest\x1a!.api.track.v1.CompleteUploadReply\"#\x82\xd3\xe4\x93\x02\x1d:\x01*\"\x18/v1/tracks/{id}/complete\x12`\n" +
	"\n" +
	"ListTracks\x12\x1f.api.track.v1.ListTracksRequest\x1a\x1d.api.track.v1.ListTracksReply\"\x12\x82\xd3\xe4\x93\x02\f\x12\n" +
	"/v1/tracks\x12[\n" +
	"\bGetTrack\x12\x1d.api.track.v1.GetTrackRequest\x1a\x17.api.track.v1.TrackInfo\"\x17\x82\xd3\xe4\x93\x02\x11\x12\x0f/v1/tracks/{id}\x12[\n" +
	"\x0fReportProcessed\x12$.api.track.v1.ReportProcessedRequest\x1a\".api.track.v1.ReportProcessedReplyB5Z3github.com/YansIlinta/wavehub-micro/api/track/v1;v1b\x06proto3"

var (
	file_api_track_v1_track_proto_rawDescOnce sync.Once
	file_api_track_v1_track_proto_rawDescData []byte
)

func file_api_track_v1_track_proto_rawDescGZIP() []byte {
	file_api_track_v1_track_proto_rawDescOnce.Do(func() {
		file_api_track_v1_track_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_track_v1_track_proto_rawDesc), len(file_api_track_v1_track_proto_rawDesc)))
	})
	return file_api_track_v1_track_proto_rawDescData
}

var file_api_track_v1_track_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_api_track_v1_track_proto_goTypes = []any{
	(*CreateTrackRequest)(nil),     // 0: api.track.v1.CreateTrackRequest
	(*CreateTrackReply)(nil),       // 1: api.track.v1.CreateTrackReply
	(*CompleteUploadRequest)(nil),  // 2: api.track.v1.CompleteUploadRequest
	(*CompleteUploadReply)(nil),    // 3: api.track.v1.CompleteUploadReply
	(*ListTracksRequest)(nil),      // 4: api.track.v1.ListTracksRequest
	(*TrackInfo)(nil),              // 5: api.track.v1.TrackInfo
	(*ListTracksReply)(nil),        // 6: api.track.v1.ListTracksReply
	(*GetTrackRequest)(nil),        // 7: api.track.v1.GetTrackRequest
	(*ReportProcessedRequest)(nil), // 8: api.track.v1.ReportProcessedRequest
	(*ReportProcessedReply)(nil),   // 9: api.track.v1.ReportProcessedReply
}
var file_api_track_v1_track_proto_depIdxs = []int32{
	5, // 0: api.track.v1.ListTracksReply.list:type_name -> api.track.v1.TrackInfo
	0, // 1: api.track.v1.Track.CreateTrack:input_type -> api.track.v1.CreateTrackRequest
	2, // 2: api.track.v1.Track.CompleteUpload:input_type -> api.track.v1.CompleteUploadRequest
	4, // 3: api.track.v1.Track.ListTracks:input_type -> api.track.v1.ListTracksRequest
	7, // 4: api.track.v1.Track.GetTrack:input_type -> api.track.v1.GetTrackRequest
	8, // 5: api.track.v1.Track.ReportProcessed:input_type -> api.track.v1.ReportProcessedRequest
	1, // 6: api.track.v1.Track.CreateTrack:output_type -> api.track.v1.CreateTrackReply
	3, // 7: api.track.v1.Track.CompleteUpload:output_type -> api.track.v1.CompleteUploadReply
	6, // 8: api.track.v1.Track.ListTracks:output_type -> api.track.v1.ListTracksReply
	5, // 9: api.track.v1.Track.GetTrack:output_type -> api.track.v1.TrackInfo
	9, // 10: api.track.v1.Track.ReportProcessed:output_type -> api.track.v1.ReportProcessedReply
	6, // [6:11] is the sub-list for method output_type
	1, // [1:6] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_track_v1_track_proto_init() }
func file_api_track_v1_track_proto_init() {
	if File_api_track_v1_track_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_track_v1_track_proto_rawDesc), len(file_api_track_v1_track_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_track_v1_track_proto_goTypes,
		DependencyIndexes: file_api_track_v1_track_proto_depIdxs,
		MessageInfos:      file_api_track_v1_track_proto_msgTypes,
	}.Build()
	File_api_track_v1_track_proto = out.File
	file_api_track_v1_track_proto_goTypes = nil
	file_api_track_v1_track_proto_depIdxs = nil
}
