// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v4.25.3
// source: api/track/v1/track.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Track_CreateTrack_FullMethodName     = "/api.track.v1.Track/CreateTrack"
	Track_CompleteUpload_FullMethodName  = "/api.track.v1.Track/CompleteUpload"
	Track_ListTracks_FullMethodName      = "/api.track.v1.Track/ListTracks"
	Track_GetTrack_FullMethodName        = "/api.track.v1.Track/GetTrack"
	Track_ReportProcessed_FullMethodName = "/api.track.v1.Track/ReportProcessed"
)

// TrackClient is the client API for Track service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TrackClient interface {
	CreateTrack(ctx context.Context, in *CreateTrackRequest, opts ...grpc.CallOption) (*CreateTrackReply, error)
	CompleteUpload(ctx context.Context, in *CompleteUploadRequest, opts ...grpc.CallOption) (*CompleteUploadReply, error)
	ListTracks(ctx context.Context, in *ListTracksRequest, opts ...grpc.CallOption) (*ListTracksReply, error)
	GetTrack(ctx context.Context, in *GetTrackRequest, opts ...grpc.CallOption) (*TrackInfo, error)
	// 内部接口：media worker 处理完成后回写结果。
	// 关键设计：tracks 表归 track 服务所有，media 不许直接写库，只能通过这个 RPC 回来 ——
	// "数据归属服务所有"是微服务最重要的纪律，破坏它 = 分布式单体。
	ReportProcessed(ctx context.Context, in *ReportProcessedRequest, opts ...grpc.CallOption) (*ReportProcessedReply, error)
}

type trackClient struct {
	cc grpc.ClientConnInterface
}

func NewTrackClient(cc grpc.ClientConnInterface) TrackClient {
	return &trackClient{cc}
}

func (c *trackClient) CreateTrack(ctx context.Context, in *CreateTrackRequest, opts ...grpc.CallOption) (*CreateTrackReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateTrackReply)
	err := c.cc.Invoke(ctx, Track_CreateTrack_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trackClient) CompleteUpload(ctx context.Context, in *CompleteUploadRequest, opts ...grpc.CallOption) (*CompleteUploadReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompleteUploadReply)
	err := c.cc.Invoke(ctx, Track_CompleteUpload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trackClient) ListTracks(ctx context.Context, in *ListTracksRequest, opts ...grpc.CallOption) (*ListTracksReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTracksReply)
	err := c.cc.Invoke(ctx, Track_ListTracks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trackClient) GetTrack(ctx context.Context, in *GetTrackRequest, opts ...grpc.CallOption) (*TrackInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TrackInfo)
	err := c.cc.Invoke(ctx, Track_GetTrack_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trackClient) ReportProcessed(ctx context.Context, in *ReportProcessedRequest, opts ...grpc.CallOption) (*ReportProcessedReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportProcessedReply)
	err := c.cc.Invoke(ctx, Track_ReportProcessed_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TrackServer is the server API for Track service.
// All implementations must embed UnimplementedTrackServer
// for forward compatibility.
type TrackServer interface {
	CreateTrack(context.Context, *CreateTrackRequest) (*CreateTrackReply, error)
	CompleteUpload(context.Context, *CompleteUploadRequest) (*CompleteUploadReply, error)
	ListTracks(context.Context, *ListTracksRequest) (*ListTracksReply, error)
	GetTrack(context.Context, *GetTrackRequest) (*TrackInfo, error)
	// 内部接口：media worker 处理完成后回写结果。
	// 关键设计：tracks 表归 track 服务所有，media 不许直接写库，只能通过这个 RPC 回来 ——
	// "数据归属服务所有"是微服务最重要的纪律，破坏它 = 分布式单体。
	ReportProcessed(context.Context, *ReportProcessedRequest) (*ReportProcessedReply, error)
	mustEmbedUnimplementedTrackServer()
}

// UnimplementedTrackServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTrackServer struct{}

func (UnimplementedTrackServer) CreateTrack(context.Context, *CreateTrackRequest) (*CreateTrackReply, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateTrack not implemented")
}
func (UnimplementedTrackServer) CompleteUpload(context.Context, *CompleteUploadRequest) (*CompleteUploadReply, error) {
	return nil, status.Error(codes.Unimplemented, "method CompleteUpload not implemented")
}
func (UnimplementedTrackServer) ListTracks(context.Context, *ListTracksRequest) (*ListTracksReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTracks not implemented")
}
func (UnimplementedTrackServer) GetTrack(context.Context, *GetTrackRequest) (*TrackInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTrack not implemented")
}
func (UnimplementedTrackServer) ReportProcessed(context.Context, *ReportProcessedRequest) (*ReportProcessedReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportProcessed not implemented")
}
func (UnimplementedTrackServer) mustEmbedUnimplementedTrackServer() {}
func (UnimplementedTrackServer) testEmbeddedByValue()               {}

// UnsafeTrackServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TrackServer will
// result in compilation errors.
type UnsafeTrackServer interface {
	mustEmbedUnimplementedTrackServer()
}

func RegisterTrackServer(s grpc.ServiceRegistrar, srv TrackServer) {
	// If the following call panics, it indicates UnimplementedTrackServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Track_ServiceDesc, srv)
}

func _Track_CreateTrack_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTrackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrackServer).CreateTrack(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Track_CreateTrack_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrackServer).CreateTrack(ctx, req.(*CreateTrackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Track_CompleteUpload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompleteUploadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrackServer).CompleteUpload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Track_CompleteUpload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrackServer).CompleteUpload(ctx, req.(*CompleteUploadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Track_ListTracks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTracksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrackServer).ListTracks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Track_ListTracks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrackServer).ListTracks(ctx, req.(*ListTracksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Track_GetTrack_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTrackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrackServer).GetTrack(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Track_GetTrack_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrackServer).GetTrack(ctx, req.(*GetTrackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Track_ReportProcessed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportProcessedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrackServer).ReportProcessed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Track_ReportProcessed_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrackServer).ReportProcessed(ctx, req.(*ReportProcessedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Track_ServiceDesc is the grpc.ServiceDesc for Track service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Track_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.track.v1.Track",
	HandlerType: (*TrackServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateTrack",
			Handler:    _Track_CreateTrack_Handler,
		},
		{
			MethodName: "CompleteUpload",
			Handler:    _Track_CompleteUpload_Handler,
		},
		{
			MethodName: "ListTracks",
			Handler:    _Track_ListTracks_Handler,
		},
		{
			MethodName: "GetTrack",
			Handler:    _Track_GetTrack_Handler,
		},
		{
			MethodName: "ReportProcessed",
			Handler:    _Track_ReportProcessed_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/track/v1/track.proto",
}
