// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v4.25.3
// source: api/track/v1/track.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationTrackCompleteUpload = "/api.track.v1.Track/CompleteUpload"
const OperationTrackCreateTrack = "/api.track.v1.Track/CreateTrack"
const OperationTrackGetTrack = "/api.track.v1.Track/GetTrack"
const OperationTrackListTracks = "/api.track.v1.Track/ListTracks"

type TrackHTTPServer interface {
	CompleteUpload(context.Context, *CompleteUploadRequest) (*CompleteUploadReply, error)
	CreateTrack(context.Context, *CreateTrackRequest) (*CreateTrackReply, error)
	GetTrack(context.Context, *GetTrackRequest) (*TrackInfo, error)
	ListTracks(context.Context, *ListTracksRequest) (*ListTracksReply, error)
}

func RegisterTrackHTTPServer(s *http.Server, srv TrackHTTPServer) {
	r := s.Route("/")
	r.POST("/v1/tracks", _Track_CreateTrack0_HTTP_Handler(srv))
	r.POST("/v1/tracks/{id}/complete", _Track_CompleteUpload0_HTTP_Handler(srv))
	r.GET("/v1/tracks", _Track_ListTracks0_HTTP_Handler(srv))
	r.GET("/v1/tracks/{id}", _Track_GetTrack0_HTTP_Handler(srv))
}

func _Track_CreateTrack0_HTTP_Handler(srv TrackHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateTrackRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTrackCreateTrack)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateTrack(ctx, req.(*CreateTrackRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateTrackReply)
		return ctx.Result(200, reply)
	}
}

func _Track_CompleteUpload0_HTTP_Handler(srv TrackHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CompleteUploadRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTrackCompleteUpload)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CompleteUpload(ctx, req.(*CompleteUploadRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CompleteUploadReply)
		return ctx.Result(200, reply)
	}
}

func _Track_ListTracks0_HTTP_Handler(srv TrackHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListTracksRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTrackListTracks)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListTracks(ctx, req.(*ListTracksRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListTracksReply)
		return ctx.Result(200, reply)
	}
}

func _Track_GetTrack0_HTTP_Handler(srv TrackHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetTrackRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTrackGetTrack)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetTrack(ctx, req.(*GetTrackRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*TrackInfo)
		return ctx.Result(200, reply)
	}
}

type TrackHTTPClient interface {
	CompleteUpload(ctx context.Context, req *CompleteUploadRequest, opts ...http.CallOption) (rsp *CompleteUploadReply, err error)
	CreateTrack(ctx context.Context, req *CreateTrackRequest, opts ...http.CallOption) (rsp *CreateTrackReply, err error)
	GetTrack(ctx context.Context, req *GetTrackRequest, opts ...http.CallOption) (rsp *TrackInfo, err error)
	ListTracks(ctx context.Context, req *ListTracksRequest, opts ...http.CallOption) (rsp *ListTracksReply, err error)
}

type TrackHTTPClientImpl struct {
	cc *http.Client
}

func NewTrackHTTPClient(client *http.Client) TrackHTTPClient {
	return &TrackHTTPClientImpl{client}
}

func (c *TrackHTTPClientImpl) CompleteUpload(ctx context.Context, in *CompleteUploadRequest, opts ...http.CallOption) (*CompleteUploadReply, error) {
	var out CompleteUploadReply
	pattern := "/v1/tracks/{id}/complete"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationTrackCompleteUpload))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *TrackHTTPClientImpl) CreateTrack(ctx context.Context, in *CreateTrackRequest, opts ...http.CallOption) (*CreateTrackReply, error) {
	var out CreateTrackReply
	pattern := "/v1/tracks"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationTrackCreateTrack))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *TrackHTTPClientImpl) GetTrack(ctx context.Context, in *GetTrackRequest, opts ...http.CallOption) (*TrackInfo, error) {
	var out TrackInfo
	pattern := "/v1/tracks/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationTrackGetTrack))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *TrackHTTPClientImpl) ListTracks(ctx context.Context, in *ListTracksRequest, opts ...http.CallOption) (*ListTracksReply, error) {
	var out ListTracksReply
	pattern := "/v1/tracks"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationTrackListTracks))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
