// X-Plore 点播视频服务契约。
// room_id 约定：字符串形式的 video_id（如 "42"），弹幕 comet 房间与稿件 1:1。

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: video/v1/video.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateVideoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Category      string                 `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"` // 分区，如 tech / anime / music
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateVideoRequest) Reset() {
	*x = CreateVideoRequest{}
	mi := &file_video_v1_video_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVideoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVideoRequest) ProtoMessage() {}

func (x *CreateVideoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_video_v1_video_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVideoRequest.ProtoReflect.Descriptor instead.
func (*CreateVideoRequest) Descriptor() ([]byte, []int) {
	return file_video_v1_video_proto_rawDescGZIP(), []int{0}
}

func (x *CreateVideoRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateVideoRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateVideoRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

type CreateVideoReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UploadUrl     string                 `protobuf:"bytes,2,opt,name=upload_url,json=uploadUrl,proto3" json:"upload_url,omitempty"` // MinIO 预签名 PUT
	RoomId        string                 `protobuf:"bytes,3,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`          // 弹幕房间 = 字符串 video id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateVideoReply) Reset() {
	*x = CreateVideoReply{}
	mi := &file_video_v1_video_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVideoReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVideoReply) ProtoMessage() {}

func (x *CreateVideoReply) ProtoReflect() protoreflect.Message {
	mi := &file_video_v1_video_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVideoReply.ProtoReflect.Descriptor instead.
func (*CreateVideoReply) Descriptor() ([]byte, []int) {
	return file_video_v1_video_proto_rawDescGZIP(), []int{1}
}

func (x *CreateVideoReply) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CreateVideoReply) GetUploadUrl() string {
	if x != nil {
		return x.UploadUrl
	}
	return ""
}

func (x *CreateVideoReply) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

type CompleteUploadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteUploadRequest) Reset() {
	*x = CompleteUploadRequest{}
	mi := &file_video_v1_video_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteUploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteUploadRequest) ProtoMessage() {}

func (x *CompleteUploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_video_v1_video_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteUploadRequest.ProtoReflect.Descriptor instead.
func (*CompleteUploadRequest) Descriptor() ([]byte, []int) {
	return file_video_v1_video_proto_rawDescGZIP(), []int{2}
}

func (x *CompleteUploadRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type CompleteUploadReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"` // processing
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteUploadReply) Reset() {
	*x = CompleteUploadReply{}
	mi := &file_video_v1_video_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteUploadReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteUploadReply) ProtoMessage() {}

func (x *CompleteUploadReply) ProtoReflect() protoreflect.Message {
	mi := &file_video_v1_video_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteUploadReply.ProtoReflect.Descriptor instead.
func (*CompleteUploadReply) Descriptor() ([]byte, []int) {
	return file_video_v1_video_proto_rawDescGZIP(), []int{3}
}

func (x *CompleteUploadReply) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ListVideosRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Size          int32                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Category      string                 `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	UserId        uint64                 `protobuf:"varint,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // 按 UP 主过滤(个人空间公开投稿列表)
	Sort          string                 `protobuf:"bytes,5,opt,name=sort,proto3" json:"sort,omitempty"`                    // ""|"new" 最新;"hot" 按 play_count+3*like 加权
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVideosRequest) Reset() {
	*x = ListVideosRequest{}
	mi := &file_video_v1_video_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVideosRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVideosRequest) ProtoMessage() {}

func (x *ListVideosRequest) ProtoReflect() protoreflect.Message {
	mi := &file_video_v1_video_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVideosRequest.ProtoReflect.Descriptor instead.
func (*ListVideosRequest) Descriptor() ([]byte, []int) {
	return file_video_v1_video_proto_rawDescGZIP(), []int{4}
}

func (x *ListVideosRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListVideosRequest) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *ListVideosRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *ListVideosRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ListVideosRequest) GetSort() string {
	if x != nil {
		return x.Sort
	}
	return ""
}

type ListRelatedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"` // 默认 12,最大 30
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRelatedRequest) Reset() {
	*x = ListRelatedRequest{}
	mi := &file_video_v1_video_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRelatedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRelatedRequest) ProtoMessage() {}

func (x *ListRelatedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_video_v1_video_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRelatedRequest.ProtoReflect.Descriptor instead.
func (*ListRelatedRequest) Descriptor() ([]byte, []int) {
	return file_video_v1_video_proto_rawDescGZIP(), []int{5}
}

func (x *ListRelatedRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ListRelatedRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListMyVideosRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Size          int32                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMyVideosRequest) Reset() {
	*x = ListMyVideosRequest{}
	mi := &file_video_v1_video_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMyVideosRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMyVideosRequest) ProtoMessage() {}

func (x *ListMyVideosRequest) ProtoReflect() protoreflect.Message {
	mi := &file_video_v1_video_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMyVideosRequest.ProtoReflect.Descriptor instead.
func (*ListMyVideosRequest) Descriptor() ([]byte, []int) {
	return file_video_v1_video_proto_rawDescGZIP(), []int{6}
}

func (x *ListMyVideosRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListMyVideosRequest) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type GetVideoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVideoRequest) Reset() {
	*x = GetVideoRequest{}
	mi := &file_video_v1_video_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVideoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVideoRequest) ProtoMessage() {}

func (x *GetVideoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_video_v1_video_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVideoRequest.ProtoReflect.Descriptor instead.
func (*GetVideoRequest) Descriptor() ([]byte, []int) {
	return file_video_v1_video_proto_rawDescGZIP(), []int{7}
}

func (x *GetVideoRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type VideoInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Category      string                 `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`
	UserId        uint64                 `protobuf:"varint,5,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Author        string                 `protobuf:"bytes,6,opt,name=author,proto3" json:"author,omitempty"`
	Status        string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"` // uploading / processing / ready / failed
	DurationSec   float64                `protobuf:"fixed64,8,opt,name=duration_sec,json=durationSec,proto3" json:"duration_sec,omitempty"`
	PlayCount     int64                  `protobuf:"varint,9,opt,name=play_count,json=playCount,proto3" json:"play_count,omitempty"`
	CoverUrl      string                 `protobuf:"bytes,10,opt,name=cover_url,json=coverUrl,proto3" json:"cover_url,omitempty"`            // 预签名封面
	PlaylistUrl   string                 `protobuf:"bytes,11,opt,name=playlist_url,json=playlistUrl,proto3" json:"playlist_url,omitempty"`   // 预签名 HLS master/playlist m3u8
	RoomId        string                 `protobuf:"bytes,12,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`                  // 弹幕房间 id
	DanmuWsHint   string                 `protobuf:"bytes,13,opt,name=danmu_ws_hint,json=danmuWsHint,proto3" json:"danmu_ws_hint,omitempty"` // 可选：文档化的 WS 入口提示，如 ws://host/ws
	LikeCount     int64                  `protobuf:"varint,14,opt,name=like_count,json=likeCount,proto3" json:"like_count,omitempty"`
	CommentCount  int64                  `protobuf:"varint,15,opt,name=comment_count,json=commentCount,proto3" json:"comment_count,omitempty"`
	FavoriteCount int64                  `protobuf:"varint,16,opt,name=favorite_count,json=favoriteCount,proto3" json:"favorite_count,omitempty"`
	Liked         bool                   `protobuf:"varint,17,opt,name=liked,proto3" json:"liked,omitempty"`         // 当前用户是否点赞（未登录 false）
	Favorited     bool                   `protobuf:"varint,18,opt,name=favorited,proto3" json:"favorited,omitempty"` // 当前用户是否收藏
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VideoInfo) Reset() {
	*x = VideoInfo{}
	mi := &file_video_v1_video_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoInfo) ProtoMessage() {}

func (x *VideoInfo) ProtoReflect() protoreflect.Message {
	mi := &file_video_v1_video_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoInfo.ProtoReflect.Descriptor instead.
func (*VideoInfo) Descriptor() ([]byte, []int) {
	return file_video_v1_video_proto_rawDescGZIP(), []int{8}
}

func (x *VideoInfo) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *VideoInfo) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *VideoInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *VideoInfo) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *VideoInfo) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *VideoInfo) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *VideoInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *VideoInfo) GetDurationSec() float64 {
	if x != nil {
		return x.DurationSec
	}
	return 0
}

func (x *VideoInfo) GetPlayCount() int64 {
	if x != nil {
		return x.PlayCount
	}
	return 0
}

func (x *VideoInfo) GetCoverUrl() string {
	if x != nil {
		return x.CoverUrl
	}
	return ""
}

func (x *VideoInfo) GetPlaylistUrl() string {
	if x != nil {
		return x.PlaylistUrl
	}
	return ""
}

func (x *VideoInfo) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *VideoInfo) GetDanmuWsHint() string {
	if x != nil {
		return x.DanmuWsHint
	}
	return ""
}

func (x *VideoInfo) GetLikeCount() int64 {
	if x != nil {
		return x.LikeCount
	}
	return 0
}

func (x *VideoInfo) GetCommentCount() int64 {
	if x != nil {
		return x.CommentCount
	}
	return 0
}

func (x *VideoInfo) GetFavoriteCount() int64 {
	if x != nil {
		return x.FavoriteCount
	}
	return 0
}

func (x *VideoInfo) GetLiked() bool {
	if x != nil {
		return x.Liked
	}
	return false
}

func (x *VideoInfo) GetFavorited() bool {
	if x != nil {
		return x.Favorited
	}
	return false
}

type ListVideosReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*VideoInfo           `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVideosReply) Reset() {
	*x = ListVideosReply{}
	mi := &file_video_v1_video_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVideosReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVideosReply) ProtoMessage() {}

func (x *ListVideosReply) ProtoReflect() protoreflect.Message {
	mi := &file_video_v1_video_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVideosReply.ProtoReflect.Descriptor instead.
func (*ListVideosReply) Descriptor() ([]byte, []int) {
	return file_video_v1_video_proto_rawDescGZIP(), []int{9}
}

func (x *ListVideosReply) GetList() []*VideoInfo {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *ListVideosReply) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type ReportProcessedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	DurationSec   float64                `protobuf:"fixed64,3,opt,name=duration_sec,json=durationSec,proto3" json:"duration_sec,omitempty"`
	PlaylistKey   string                 `protobuf:"bytes,4,opt,name=playlist_key,json=playlistKey,proto3" json:"playlist_key,omitempty"` // 如 videos/42/hls/index.m3u8
	CoverKey      string                 `protobuf:"bytes,5,opt,name=cover_key,json=coverKey,proto3" json:"cover_key,omitempty"`          // 如 videos/42/cover.jpg
	ErrorMessage  string                 `protobuf:"bytes,6,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportProcessedRequest) Reset() {
	*x = ReportProcessedRequest{}
	mi := &file_video_v1_video_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportProcessedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportProcessedRequest) ProtoMessage() {}

func (x *ReportProcessedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_video_v1_video_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportProcessedRequest.ProtoReflect.Descriptor instead.
func (*ReportProcessedRequest) Descriptor() ([]byte, []int) {
	return file_video_v1_video_proto_rawDescGZIP(), []int{10}
}

func (x *ReportProcessedRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ReportProcessedRequest) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ReportProcessedRequest) GetDurationSec() float64 {
	if x != nil {
		return x.DurationSec
	}
	return 0
}

func (x *ReportProcessedRequest) GetPlaylistKey() string {
	if x != nil {
		return x.PlaylistKey
	}
	return ""
}

func (x *ReportProcessedRequest) GetCoverKey() string {
	if x != nil {
		return x.CoverKey
	}
	return ""
}

func (x *ReportProcessedRequest) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type ReportProcessedReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportProcessedReply) Reset() {
	*x = ReportProcessedReply{}
	mi := &file_video_v1_video_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportProcessedReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportProcessedReply) ProtoMessage() {}

func (x *ReportProcessedReply) ProtoReflect() protoreflect.Message {
	mi := &file_video_v1_video_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportProcessedReply.ProtoReflect.Descriptor instead.
func (*ReportProcessedReply) Descriptor() ([]byte, []int) {
	return file_video_v1_video_proto_rawDescGZIP(), []int{11}
}

type ListDanmuRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                       // video id（= room_id 数字）
	FromMs        int64                  `protobuf:"varint,2,opt,name=from_ms,json=fromMs,proto3" json:"from_ms,omitempty"` // 含，播放进度毫秒，默认 0
	ToMs          int64                  `protobuf:"varint,3,opt,name=to_ms,json=toMs,proto3" json:"to_ms,omitempty"`       // 含，0 表示不限上界
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`                 // 默认 200，最大 1000
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDanmuRequest) Reset() {
	*x = ListDanmuRequest{}
	mi := &file_video_v1_video_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDanmuRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDanmuRequest) ProtoMessage() {}

func (x *ListDanmuRequest) ProtoReflect() protoreflect.Message {
	mi := &file_video_v1_video_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDanmuRequest.ProtoReflect.Descriptor instead.
func (*ListDanmuRequest) Descriptor() ([]byte, []int) {
	return file_video_v1_video_proto_rawDescGZIP(), []int{12}
}

func (x *ListDanmuRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ListDanmuRequest) GetFromMs() int64 {
	if x != nil {
		return x.FromMs
	}
	return 0
}

func (x *ListDanmuRequest) GetToMs() int64 {
	if x != nil {
		return x.ToMs
	}
	return 0
}

func (x *ListDanmuRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type DanmuItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MsgId         string                 `protobuf:"bytes,1,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	Uid           string                 `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	OffsetMs      int64                  `protobuf:"varint,4,opt,name=offset_ms,json=offsetMs,proto3" json:"offset_ms,omitempty"`    // 相对视频起始的毫秒
	CreatedAt     int64                  `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // unix ms
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DanmuItem) Reset() {
	*x = DanmuItem{}
	mi := &file_video_v1_video_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DanmuItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DanmuItem) ProtoMessage() {}

func (x *DanmuItem) ProtoReflect() protoreflect.Message {
	mi := &file_video_v1_video_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DanmuItem.ProtoReflect.Descriptor instead.
func (*DanmuItem) Descriptor() ([]byte, []int) {
	return file_video_v1_video_proto_rawDescGZIP(), []int{13}
}

func (x *DanmuItem) GetMsgId() string {
	if x != nil {
		return x.MsgId
	}
	return ""
}

func (x *DanmuItem) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *DanmuItem) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *DanmuItem) GetOffsetMs() int64 {
	if x != nil {
		return x.OffsetMs
	}
	return 0
}

func (x *DanmuItem) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type ListDanmuReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*DanmuItem           `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDanmuReply) Reset() {
	*x = ListDanmuReply{}
	mi := &file_video_v1_video_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDanmuReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDanmuReply) ProtoMessage() {}

func (x *ListDanmuReply) ProtoReflect() protoreflect.Message {
	mi := &file_video_v1_video_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDanmuReply.ProtoReflect.Descriptor instead.
func (*ListDanmuReply) Descriptor() ([]byte, []int) {
	return file_video_v1_video_proto_rawDescGZIP(), []int{14}
}

func (x *ListDanmuReply) GetList() []*DanmuItem {
	if x != nil {
		return x.List
	}
	return nil
}

type PostDanmuRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	OffsetMs      int64                  `protobuf:"varint,3,opt,name=offset_ms,json=offsetMs,proto3" json:"offset_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostDanmuRequest) Reset() {
	*x = PostDanmuRequest{}
	mi := &file_video_v1_video_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostDanmuRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostDanmuRequest) ProtoMessage() {}

func (x *PostDanmuRequest) ProtoReflect() protoreflect.Message {
	mi := &file_video_v1_video_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostDanmuRequest.ProtoReflect.Descriptor instead.
func (*PostDanmuRequest) Descriptor() ([]byte, []int) {
	return file_video_v1_video_proto_rawDescGZIP(), []int{15}
}

func (x *PostDanmuRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PostDanmuRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *PostDanmuRequest) GetOffsetMs() int64 {
	if x != nil {
		return x.OffsetMs
	}
	return 0
}

type PostDanmuReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MsgId         string                 `protobuf:"bytes,1,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	OffsetMs      int64                  `protobuf:"varint,2,opt,name=offset_ms,json=offsetMs,proto3" json:"offset_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostDanmuReply) Reset() {
	*x = PostDanmuReply{}
	mi := &file_video_v1_video_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostDanmuReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostDanmuReply) ProtoMessage() {}

func (x *PostDanmuReply) ProtoReflect() protoreflect.Message {
	mi := &file_video_v1_video_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostDanmuReply.ProtoReflect.Descriptor instead.
func (*PostDanmuReply) Descriptor() ([]byte, []int) {
	return file_video_v1_video_proto_rawDescGZIP(), []int{16}
}

func (x *PostDanmuReply) GetMsgId() string {
	if x != nil {
		return x.MsgId
	}
	return ""
}

func (x *PostDanmuReply) GetOffsetMs() int64 {
	if x != nil {
		return x.OffsetMs
	}
	return 0
}

type ListCommentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Size          int32                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCommentsRequest) Reset() {
	*x = ListCommentsRequest{}
	mi := &file_video_v1_video_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCommentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCommentsRequest) ProtoMessage() {}

func (x *ListCommentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_video_v1_video_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCommentsRequest.ProtoReflect.Descriptor instead.
func (*ListCommentsRequest) Descriptor() ([]byte, []int) {
	return file_video_v1_video_proto_rawDescGZIP(), []int{17}
}

func (x *ListCommentsRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ListCommentsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListCommentsRequest) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type CommentItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        uint64                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Author        string                 `protobuf:"bytes,3,opt,name=author,proto3" json:"author,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // unix ms
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommentItem) Reset() {
	*x = CommentItem{}
	mi := &file_video_v1_video_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommentItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommentItem) ProtoMessage() {}

func (x *CommentItem) ProtoReflect() protoreflect.Message {
	mi := &file_video_v1_video_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommentItem.ProtoReflect.Descriptor instead.
func (*CommentItem) Descriptor() ([]byte, []int) {
	return file_video_v1_video_proto_rawDescGZIP(), []int{18}
}

func (x *CommentItem) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CommentItem) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CommentItem) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *CommentItem) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CommentItem) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type ListCommentsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*CommentItem         `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCommentsReply) Reset() {
	*x = ListCommentsReply{}
	mi := &file_video_v1_video_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCommentsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCommentsReply) ProtoMessage() {}

func (x *ListCommentsReply) ProtoReflect() protoreflect.Message {
	mi := &file_video_v1_video_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCommentsReply.ProtoReflect.Descriptor instead.
func (*ListCommentsReply) Descriptor() ([]byte, []int) {
	return file_video_v1_video_proto_rawDescGZIP(), []int{19}
}

func (x *ListCommentsReply) GetList() []*CommentItem {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *ListCommentsReply) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type PostCommentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostCommentRequest) Reset() {
	*x = PostCommentRequest{}
	mi := &file_video_v1_video_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostCommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostCommentRequest) ProtoMessage() {}

func (x *PostCommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_video_v1_video_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostCommentRequest.ProtoReflect.Descriptor instead.
func (*PostCommentRequest) Descriptor() ([]byte, []int) {
	return file_video_v1_video_proto_rawDescGZIP(), []int{20}
}

func (x *PostCommentRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PostCommentRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type PostCommentReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostCommentReply) Reset() {
	*x = PostCommentReply{}
	mi := &file_video_v1_video_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostCommentReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostCommentReply) ProtoMessage() {}

func (x *PostCommentReply) ProtoReflect() protoreflect.Message {
	mi := &file_video_v1_video_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostCommentReply.ProtoReflect.Descriptor instead.
func (*PostCommentReply) Descriptor() ([]byte, []int) {
	return file_video_v1_video_proto_rawDescGZIP(), []int{21}
}

func (x *PostCommentReply) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ToggleLikeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToggleLikeRequest) Reset() {
	*x = ToggleLikeRequest{}
	mi := &file_video_v1_video_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToggleLikeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToggleLikeRequest) ProtoMessage() {}

func (x *ToggleLikeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_video_v1_video_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToggleLikeRequest.ProtoReflect.Descriptor instead.
func (*ToggleLikeRequest) Descriptor() ([]byte, []int) {
	return file_video_v1_video_proto_rawDescGZIP(), []int{22}
}

func (x *ToggleLikeRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ToggleLikeReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Liked         bool                   `protobuf:"varint,1,opt,name=liked,proto3" json:"liked,omitempty"`
	LikeCount     int64                  `protobuf:"varint,2,opt,name=like_count,json=likeCount,proto3" json:"like_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToggleLikeReply) Reset() {
	*x = ToggleLikeReply{}
	mi := &file_video_v1_video_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToggleLikeReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToggleLikeReply) ProtoMessage() {}

func (x *ToggleLikeReply) ProtoReflect() protoreflect.Message {
	mi := &file_video_v1_video_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToggleLikeReply.ProtoReflect.Descriptor instead.
func (*ToggleLikeReply) Descriptor() ([]byte, []int) {
	return file_video_v1_video_proto_rawDescGZIP(), []int{23}
}

func (x *ToggleLikeReply) GetLiked() bool {
	if x != nil {
		return x.Liked
	}
	return false
}

func (x *ToggleLikeReply) GetLikeCount() int64 {
	if x != nil {
		return x.LikeCount
	}
	return 0
}

type ToggleFavoriteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToggleFavoriteRequest) Reset() {
	*x = ToggleFavoriteRequest{}
	mi := &file_video_v1_video_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToggleFavoriteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToggleFavoriteRequest) ProtoMessage() {}

func (x *ToggleFavoriteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_video_v1_video_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToggleFavoriteRequest.ProtoReflect.Descriptor instead.
func (*ToggleFavoriteRequest) Descriptor() ([]byte, []int) {
	return file_video_v1_video_proto_rawDescGZIP(), []int{24}
}

func (x *ToggleFavoriteRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ToggleFavoriteReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Favorited     bool                   `protobuf:"varint,1,opt,name=favorited,proto3" json:"favorited,omitempty"`
	FavoriteCount int64                  `protobuf:"varint,2,opt,name=favorite_count,json=favoriteCount,proto3" json:"favorite_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToggleFavoriteReply) Reset() {
	*x = ToggleFavoriteReply{}
	mi := &file_video_v1_video_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToggleFavoriteReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToggleFavoriteReply) ProtoMessage() {}

func (x *ToggleFavoriteReply) ProtoReflect() protoreflect.Message {
	mi := &file_video_v1_video_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToggleFavoriteReply.ProtoReflect.Descriptor instead.
func (*ToggleFavoriteReply) Descriptor() ([]byte, []int) {
	return file_video_v1_video_proto_rawDescGZIP(), []int{25}
}

func (x *ToggleFavoriteReply) GetFavorited() bool {
	if x != nil {
		return x.Favorited
	}
	return false
}

func (x *ToggleFavoriteReply) GetFavoriteCount() int64 {
	if x != nil {
		return x.FavoriteCount
	}
	return 0
}

type GetInteractStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInteractStatsRequest) Reset() {
	*x = GetInteractStatsRequest{}
	mi := &file_video_v1_video_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInteractStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInteractStatsRequest) ProtoMessage() {}

func (x *GetInteractStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_video_v1_video_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInteractStatsRequest.ProtoReflect.Descriptor instead.
func (*GetInteractStatsRequest) Descriptor() ([]byte, []int) {
	return file_video_v1_video_proto_rawDescGZIP(), []int{26}
}

func (x *GetInteractStatsRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type InteractStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LikeCount     int64                  `protobuf:"varint,1,opt,name=like_count,json=likeCount,proto3" json:"like_count,omitempty"`
	CommentCount  int64                  `protobuf:"varint,2,opt,name=comment_count,json=commentCount,proto3" json:"comment_count,omitempty"`
	FavoriteCount int64                  `protobuf:"varint,3,opt,name=favorite_count,json=favoriteCount,proto3" json:"favorite_count,omitempty"`
	Liked         bool                   `protobuf:"varint,4,opt,name=liked,proto3" json:"liked,omitempty"`
	Favorited     bool                   `protobuf:"varint,5,opt,name=favorited,proto3" json:"favorited,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InteractStats) Reset() {
	*x = InteractStats{}
	mi := &file_video_v1_video_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InteractStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InteractStats) ProtoMessage() {}

func (x *InteractStats) ProtoReflect() protoreflect.Message {
	mi := &file_video_v1_video_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InteractStats.ProtoReflect.Descriptor instead.
func (*InteractStats) Descriptor() ([]byte, []int) {
	return file_video_v1_video_proto_rawDescGZIP(), []int{27}
}

func (x *InteractStats) GetLikeCount() int64 {
	if x != nil {
		return x.LikeCount
	}
	return 0
}

func (x *InteractStats) GetCommentCount() int64 {
	if x != nil {
		return x.CommentCount
	}
	return 0
}

func (x *InteractStats) GetFavoriteCount() int64 {
	if x != nil {
		return x.FavoriteCount
	}
	return 0
}

func (x *InteractStats) GetLiked() bool {
	if x != nil {
		return x.Liked
	}
	return false
}

func (x *InteractStats) GetFavorited() bool {
	if x != nil {
		return x.Favorited
	}
	return false
}

var File_video_v1_video_proto protoreflect.FileDescriptor

const file_video_v1_video_proto_rawDesc = "" +
	"\n" +
	"\x14video/v1/video.proto\x12\fapi.video.v1\x1a\x1cgoogle/api/annotations.proto\"h\n" +
	"\x12CreateVideoRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1a\n" +
	"\bcategory\x18\x03 \x01(\tR\bcategory\"Z\n" +
	"\x10CreateVideoReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x1d\n" +
	"\n" +
	"upload_url\x18\x02 \x01(\tR\tuploadUrl\x12\x17\n" +
	"\aroom_id\x18\x03 \x01(\tR\x06roomId\"9\n" +
	"\x15CompleteUploadRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02idJ\x04\b\x02\x10\x03R\n" +
	"object_key\"-\n" +
	"\x13CompleteUploadReply\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"\x84\x01\n" +
	"\x11ListVideosRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x05R\x04size\x12\x1a\n" +
	"\bcategory\x18\x03 \x01(\tR\bcategory\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\x04R\x06userId\x12\x12\n" +
	"\x04sort\x18\x05 \x01(\tR\x04sort\":\n" +
	"\x12ListRelatedRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"=\n" +
	"\x13ListMyVideosRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x05R\x04size\"!\n" +
	"\x0fGetVideoRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"\x96\x04\n" +
	"\tVideoInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1a\n" +
	"\bcategory\x18\x04 \x01(\tR\bcategory\x12\x17\n" +
	"\auser_id\x18\x05 \x01(\x04R\x06userId\x12\x16\n" +
	"\x06author\x18\x06 \x01(\tR\x06author\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12!\n" +
	"\fduration_sec\x18\b \x01(\x01R\vdurationSec\x12\x1d\n" +
	"\n" +
	"play_count\x18\t \x01(\x03R\tplayCount\x12\x1b\n" +
	"\tcover_url\x18\n" +
	" \x01(\tR\bcoverUrl\x12!\n" +
	"\fplaylist_url\x18\v \x01(\tR\vplaylistUrl\x12\x17\n" +
	"\aroom_id\x18\f \x01(\tR\x06roomId\x12\"\n" +
	"\rdanmu_ws_hint\x18\r \x01(\tR\vdanmuWsHint\x12\x1d\n" +
	"\n" +
	"like_count\x18\x0e \x01(\x03R\tlikeCount\x12#\n" +
	"\rcomment_count\x18\x0f \x01(\x03R\fcommentCount\x12%\n" +
	"\x0efavorite_count\x18\x10 \x01(\x03R\rfavoriteCount\x12\x14\n" +
	"\x05liked\x18\x11 \x01(\bR\x05liked\x12\x1c\n" +
	"\tfavorited\x18\x12 \x01(\bR\tfavorited\"T\n" +
	"\x0fListVideosReply\x12+\n" +
	"\x04list\x18\x01 \x03(\v2\x17.api.video.v1.VideoInfoR\x04list\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"\xca\x01\n" +
	"\x16ReportProcessedRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12!\n" +
	"\fduration_sec\x18\x03 \x01(\x01R\vdurationSec\x12!\n" +
	"\fplaylist_key\x18\x04 \x01(\tR\vplaylistKey\x12\x1b\n" +
	"\tcover_key\x18\x05 \x01(\tR\bcoverKey\x12#\n" +
	"\rerror_message\x18\x06 \x01(\tR\ferrorMessage\"\x16\n" +
	"\x14ReportProcessedReply\"f\n" +
	"\x10ListDanmuRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x17\n" +
	"\afrom_ms\x18\x02 \x01(\x03R\x06fromMs\x12\x13\n" +
	"\x05to_ms\x18\x03 \x01(\x03R\x04toMs\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\"\x8a\x01\n" +
	"\tDanmuItem\x12\x15\n" +
	"\x06msg_id\x18\x01 \x01(\tR\x05msgId\x12\x10\n" +
	"\x03uid\x18\x02 \x01(\tR\x03uid\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x1b\n" +
	"\toffset_ms\x18\x04 \x01(\x03R\boffsetMs\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\x03R\tcreatedAt\"=\n" +
	"\x0eListDanmuReply\x12+\n" +
	"\x04list\x18\x01 \x03(\v2\x17.api.video.v1.DanmuItemR\x04list\"Y\n" +
	"\x10PostDanmuRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x1b\n" +
	"\toffset_ms\x18\x03 \x01(\x03R\boffsetMs\"D\n" +
	"\x0ePostDanmuReply\x12\x15\n" +
	"\x06msg_id\x18\x01 \x01(\tR\x05msgId\x12\x1b\n" +
	"\toffset_ms\x18\x02 \x01(\x03R\boffsetMs\"M\n" +
	"\x13ListCommentsRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x05R\x04size\"\x87\x01\n" +
	"\vCommentItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x04R\x06userId\x12\x16\n" +
	"\x06author\x18\x03 \x01(\tR\x06author\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\x03R\tcreatedAt\"X\n" +
	"\x11ListCommentsReply\x12-\n" +
	"\x04list\x18\x01 \x03(\v2\x19.api.video.v1.CommentItemR\x04list\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\">\n" +
	"\x12PostCommentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"\"\n" +
	"\x10PostCommentReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"#\n" +
	"\x11ToggleLikeRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"F\n" +
	"\x0fToggleLikeReply\x12\x14\n" +
	"\x05liked\x18\x01 \x01(\bR\x05liked\x12\x1d\n" +
	"\n" +
	"like_count\x18\x02 \x01(\x03R\tlikeCount\"'\n" +
	"\x15ToggleFavoriteRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"Z\n" +
	"\x13ToggleFavoriteReply\x12\x1c\n" +
	"\tfavorited\x18\x01 \x01(\bR\tfavorited\x12%\n" +
	"\x0efavorite_count\x18\x02 \x01(\x03R\rfavoriteCount\")\n" +
	"\x17GetInteractStatsRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"\xae\x01\n" +
	"\rInteractStats\x12\x1d\n" +
	"\n" +
	"like_count\x18\x01 \x01(\x03R\tlikeCount\x12#\n" +
	"\rcomment_count\x18\x02 \x01(\x03R\fcommentCount\x12%\n" +
	"\x0efavorite_count\x18\x03 \x01(\x03R\rfavoriteCount\x12\x14\n" +
	"\x05liked\x18\x04 \x01(\bR\x05liked\x12\x1c\n" +
	"\tfavorited\x18\x05 \x01(\bR\tfavorited2\x8c\f\n" +
	"\x05Video\x12f\n" +
	"\vCreateVideo\x12 .api.video.v1.CreateVideoRequest\x1a\x1e.api.video.v1.CreateVideoReply\"\x15\x82\xd3\xe4\x93\x02\x0f:\x01*\"\n" +
	"/v1/videos\x12}\n" +
	"\x0eCompleteUpload\x12#.api.video.v1.CompleteUploadRequest\x1a!.api.video.v1.CompleteUploadReply\"#\x82\xd3\xe4\x93\x02\x1d:\x01*\"\x18/v1/videos/{id}/complete\x12`\n" +
	"\n" +
	"ListVideos\x12\x1f.api.video.v1.ListVideosRequest\x1a\x1d.api.video.v1.ListVideosReply\"\x12\x82\xd3\xe4\x93\x02\f\x12\n" +
	"/v1/videos\x12o\n" +
	"\vListRelated\x12 .api.video.v1.ListRelatedRequest\x1a\x1d.api.video.v1.ListVideosReply\"\x1f\x82\xd3\xe4\x93\x02\x19\x12\x17/v1/videos/{id}/related\x12[\n" +
	"\bGetVideo\x12\x1d.api.video.v1.GetVideoRequest\x1a\x17.api.video.v1.VideoInfo\"\x17\x82\xd3\xe4\x93\x02\x11\x12\x0f/v1/videos/{id}\x12g\n" +
	"\fListMyVideos\x12!.api.video.v1.ListMyVideosRequest\x1a\x1d.api.video.v1.ListVideosReply\"\x15\x82\xd3\xe4\x93\x02\x0f\x12\r/v1/me/videos\x12h\n" +
	"\tListDanmu\x12\x1e.api.video.v1.ListDanmuRequest\x1a\x1c.api.video.v1.ListDanmuReply\"\x1d\x82\xd3\xe4\x93\x02\x17\x12\x15/v1/videos/{id}/danmu\x12k\n" +
	"\tPostDanmu\x12\x1e.api.video.v1.PostDanmuRequest\x1a\x1c.api.video.v1.PostDanmuReply\" \x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/v1/videos/{id}/danmu\x12t\n" +
	"\fListComments\x12!.api.video.v1.ListCommentsRequest\x1a\x1f.api.video.v1.ListCommentsReply\" \x82\xd3\xe4\x93\x02\x1a\x12\x18/v1/videos/{id}/comments\x12t\n" +
	"\vPostComment\x12 .api.video.v1.PostCommentRequest\x1a\x1e.api.video.v1.PostCommentReply\"#\x82\xd3\xe4\x93\x02\x1d:\x01*\"\x18/v1/videos/{id}/comments\x12m\n" +
	"\n" +
	"ToggleLike\x12\x1f.api.video.v1.ToggleLikeRequest\x1a\x1d.api.video.v1.ToggleLikeReply\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/v1/videos/{id}/like\x12}\n" +
	"\x0eToggleFavorite\x12#.api.video.v1.ToggleFavoriteRequest\x1a!.api.video.v1.ToggleFavoriteReply\"#\x82\xd3\xe4\x93\x02\x1d:\x01*\"\x18/v1/videos/{id}/favorite\x12u\n" +
	"\x10GetInteractStats\x12%.api.video.v1.GetInteractStatsRequest\x1a\x1b.api.video.v1.InteractStats\"\x1d\x82\xd3\xe4\x93\x02\x17\x12\x15/v1/videos/{id}/stats\x12[\n" +
	"\x0fReportProcessed\x12$.api.video.v1.ReportProcessedRequest\x1a\".api.video.v1.ReportProcessedReplyB5Z3github.com/YansIlinta/wavehub-micro/api/video/v1;v1b\x06proto3"

var (
	file_video_v1_video_proto_rawDescOnce sync.Once
	file_video_v1_video_proto_rawDescData []byte
)

func file_video_v1_video_proto_rawDescGZIP() []byte {
	file_video_v1_video_proto_rawDescOnce.Do(func() {
		file_video_v1_video_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_video_v1_video_proto_rawDesc), len(file_video_v1_video_proto_rawDesc)))
	})
	return file_video_v1_video_proto_rawDescData
}

var file_video_v1_video_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_video_v1_video_proto_goTypes = []any{
	(*CreateVideoRequest)(nil),      // 0: api.video.v1.CreateVideoRequest
	(*CreateVideoReply)(nil),        // 1: api.video.v1.CreateVideoReply
	(*CompleteUploadRequest)(nil),   // 2: api.video.v1.CompleteUploadRequest
	(*CompleteUploadReply)(nil),     // 3: api.video.v1.CompleteUploadReply
	(*ListVideosRequest)(nil),       // 4: api.video.v1.ListVideosRequest
	(*ListRelatedRequest)(nil),      // 5: api.video.v1.ListRelatedRequest
	(*ListMyVideosRequest)(nil),     // 6: api.video.v1.ListMyVideosRequest
	(*GetVideoRequest)(nil),         // 7: api.video.v1.GetVideoRequest
	(*VideoInfo)(nil),               // 8: api.video.v1.VideoInfo
	(*ListVideosReply)(nil),         // 9: api.video.v1.ListVideosReply
	(*ReportProcessedRequest)(nil),  // 10: api.video.v1.ReportProcessedRequest
	(*ReportProcessedReply)(nil),    // 11: api.video.v1.ReportProcessedReply
	(*ListDanmuRequest)(nil),        // 12: api.video.v1.ListDanmuRequest
	(*DanmuItem)(nil),               // 13: api.video.v1.DanmuItem
	(*ListDanmuReply)(nil),          // 14: api.video.v1.ListDanmuReply
	(*PostDanmuRequest)(nil),        // 15: api.video.v1.PostDanmuRequest
	(*PostDanmuReply)(nil),          // 16: api.video.v1.PostDanmuReply
	(*ListCommentsRequest)(nil),     // 17: api.video.v1.ListCommentsRequest
	(*CommentItem)(nil),             // 18: api.video.v1.CommentItem
	(*ListCommentsReply)(nil),       // 19: api.video.v1.ListCommentsReply
	(*PostCommentRequest)(nil),      // 20: api.video.v1.PostCommentRequest
	(*PostCommentReply)(nil),        // 21: api.video.v1.PostCommentReply
	(*ToggleLikeRequest)(nil),       // 22: api.video.v1.ToggleLikeRequest
	(*ToggleLikeReply)(nil),         // 23: api.video.v1.ToggleLikeReply
	(*ToggleFavoriteRequest)(nil),   // 24: api.video.v1.ToggleFavoriteRequest
	(*ToggleFavoriteReply)(nil),     // 25: api.video.v1.ToggleFavoriteReply
	(*GetInteractStatsRequest)(nil), // 26: api.video.v1.GetInteractStatsRequest
	(*InteractStats)(nil),           // 27: api.video.v1.InteractStats
}
var file_video_v1_video_proto_depIdxs = []int32{
	8,  // 0: api.video.v1.ListVideosReply.list:type_name -> api.video.v1.VideoInfo
	13, // 1: api.video.v1.ListDanmuReply.list:type_name -> api.video.v1.DanmuItem
	18, // 2: api.video.v1.ListCommentsReply.list:type_name -> api.video.v1.CommentItem
	0,  // 3: api.video.v1.Video.CreateVideo:input_type -> api.video.v1.CreateVideoRequest
	2,  // 4: api.video.v1.Video.CompleteUpload:input_type -> api.video.v1.CompleteUploadRequest
	4,  // 5: api.video.v1.Video.ListVideos:input_type -> api.video.v1.ListVideosRequest
	5,  // 6: api.video.v1.Video.ListRelated:input_type -> api.video.v1.ListRelatedRequest
	7,  // 7: api.video.v1.Video.GetVideo:input_type -> api.video.v1.GetVideoRequest
	6,  // 8: api.video.v1.Video.ListMyVideos:input_type -> api.video.v1.ListMyVideosRequest
	12, // 9: api.video.v1.Video.ListDanmu:input_type -> api.video.v1.ListDanmuRequest
	15, // 10: api.video.v1.Video.PostDanmu:input_type -> api.video.v1.PostDanmuRequest
	17, // 11: api.video.v1.Video.ListComments:input_type -> api.video.v1.ListCommentsRequest
	20, // 12: api.video.v1.Video.PostComment:input_type -> api.video.v1.PostCommentRequest
	22, // 13: api.video.v1.Video.ToggleLike:input_type -> api.video.v1.ToggleLikeRequest
	24, // 14: api.video.v1.Video.ToggleFavorite:input_type -> api.video.v1.ToggleFavoriteRequest
	26, // 15: api.video.v1.Video.GetInteractStats:input_type -> api.video.v1.GetInteractStatsRequest
	10, // 16: api.video.v1.Video.ReportProcessed:input_type -> api.video.v1.ReportProcessedRequest
	1,  // 17: api.video.v1.Video.CreateVideo:output_type -> api.video.v1.CreateVideoReply
	3,  // 18: api.video.v1.Video.CompleteUpload:output_type -> api.video.v1.CompleteUploadReply
	9,  // 19: api.video.v1.Video.ListVideos:output_type -> api.video.v1.ListVideosReply
	9,  // 20: api.video.v1.Video.ListRelated:output_type -> api.video.v1.ListVideosReply
	8,  // 21: api.video.v1.Video.GetVideo:output_type -> api.video.v1.VideoInfo
	9,  // 22: api.video.v1.Video.ListMyVideos:output_type -> api.video.v1.ListVideosReply
	14, // 23: api.video.v1.Video.ListDanmu:output_type -> api.video.v1.ListDanmuReply
	16, // 24: api.video.v1.Video.PostDanmu:output_type -> api.video.v1.PostDanmuReply
	19, // 25: api.video.v1.Video.ListComments:output_type -> api.video.v1.ListCommentsReply
	21, // 26: api.video.v1.Video.PostComment:output_type -> api.video.v1.PostCommentReply
	23, // 27: api.video.v1.Video.ToggleLike:output_type -> api.video.v1.ToggleLikeReply
	25, // 28: api.video.v1.Video.ToggleFavorite:output_type -> api.video.v1.ToggleFavoriteReply
	27, // 29: api.video.v1.Video.GetInteractStats:output_type -> api.video.v1.InteractStats
	11, // 30: api.video.v1.Video.ReportProcessed:output_type -> api.video.v1.ReportProcessedReply
	17, // [17:31] is the sub-list for method output_type
	3,  // [3:17] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_video_v1_video_proto_init() }
func file_video_v1_video_proto_init() {
	if File_video_v1_video_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_video_v1_video_proto_rawDesc), len(file_video_v1_video_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_video_v1_video_proto_goTypes,
		DependencyIndexes: file_video_v1_video_proto_depIdxs,
		MessageInfos:      file_video_v1_video_proto_msgTypes,
	}.Build()
	File_video_v1_video_proto = out.File
	file_video_v1_video_proto_goTypes = nil
	file_video_v1_video_proto_depIdxs = nil
}
