// X-Plore 点播视频服务契约。
// room_id 约定：字符串形式的 video_id（如 "42"），弹幕 comet 房间与稿件 1:1。

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: video/v1/video.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Video_CreateVideo_FullMethodName      = "/api.video.v1.Video/CreateVideo"
	Video_CompleteUpload_FullMethodName   = "/api.video.v1.Video/CompleteUpload"
	Video_ListVideos_FullMethodName       = "/api.video.v1.Video/ListVideos"
	Video_ListRelated_FullMethodName      = "/api.video.v1.Video/ListRelated"
	Video_GetVideo_FullMethodName         = "/api.video.v1.Video/GetVideo"
	Video_ListMyVideos_FullMethodName     = "/api.video.v1.Video/ListMyVideos"
	Video_ListDanmu_FullMethodName        = "/api.video.v1.Video/ListDanmu"
	Video_PostDanmu_FullMethodName        = "/api.video.v1.Video/PostDanmu"
	Video_ListComments_FullMethodName     = "/api.video.v1.Video/ListComments"
	Video_PostComment_FullMethodName      = "/api.video.v1.Video/PostComment"
	Video_ToggleLike_FullMethodName       = "/api.video.v1.Video/ToggleLike"
	Video_ToggleFavorite_FullMethodName   = "/api.video.v1.Video/ToggleFavorite"
	Video_GetInteractStats_FullMethodName = "/api.video.v1.Video/GetInteractStats"
	Video_ReportProcessed_FullMethodName  = "/api.video.v1.Video/ReportProcessed"
)

// VideoClient is the client API for Video service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VideoClient interface {
	CreateVideo(ctx context.Context, in *CreateVideoRequest, opts ...grpc.CallOption) (*CreateVideoReply, error)
	CompleteUpload(ctx context.Context, in *CompleteUploadRequest, opts ...grpc.CallOption) (*CompleteUploadReply, error)
	ListVideos(ctx context.Context, in *ListVideosRequest, opts ...grpc.CallOption) (*ListVideosReply, error)
	// 相关推荐:同分区按热度,排除自身(播放页侧栏)
	ListRelated(ctx context.Context, in *ListRelatedRequest, opts ...grpc.CallOption) (*ListVideosReply, error)
	GetVideo(ctx context.Context, in *GetVideoRequest, opts ...grpc.CallOption) (*VideoInfo, error)
	ListMyVideos(ctx context.Context, in *ListMyVideosRequest, opts ...grpc.CallOption) (*ListVideosReply, error)
	// 点播历史弹幕（按播放进度 offset_ms 区间拉取）
	ListDanmu(ctx context.Context, in *ListDanmuRequest, opts ...grpc.CallOption) (*ListDanmuReply, error)
	// 持久化一条点播弹幕（JWT）；实时广播仍走 comet WS
	PostDanmu(ctx context.Context, in *PostDanmuRequest, opts ...grpc.CallOption) (*PostDanmuReply, error)
	// ---- 互动（M5，同库；日后可拆 interact 服务）----
	ListComments(ctx context.Context, in *ListCommentsRequest, opts ...grpc.CallOption) (*ListCommentsReply, error)
	PostComment(ctx context.Context, in *PostCommentRequest, opts ...grpc.CallOption) (*PostCommentReply, error)
	ToggleLike(ctx context.Context, in *ToggleLikeRequest, opts ...grpc.CallOption) (*ToggleLikeReply, error)
	ToggleFavorite(ctx context.Context, in *ToggleFavoriteRequest, opts ...grpc.CallOption) (*ToggleFavoriteReply, error)
	GetInteractStats(ctx context.Context, in *GetInteractStatsRequest, opts ...grpc.CallOption) (*InteractStats, error)
	// 内部：media worker 转码完成后回写。videos 表归 video 服务，media 不得直写库。
	ReportProcessed(ctx context.Context, in *ReportProcessedRequest, opts ...grpc.CallOption) (*ReportProcessedReply, error)
}

type videoClient struct {
	cc grpc.ClientConnInterface
}

func NewVideoClient(cc grpc.ClientConnInterface) VideoClient {
	return &videoClient{cc}
}

func (c *videoClient) CreateVideo(ctx context.Context, in *CreateVideoRequest, opts ...grpc.CallOption) (*CreateVideoReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateVideoReply)
	err := c.cc.Invoke(ctx, Video_CreateVideo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *videoClient) CompleteUpload(ctx context.Context, in *CompleteUploadRequest, opts ...grpc.CallOption) (*CompleteUploadReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompleteUploadReply)
	err := c.cc.Invoke(ctx, Video_CompleteUpload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *videoClient) ListVideos(ctx context.Context, in *ListVideosRequest, opts ...grpc.CallOption) (*ListVideosReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListVideosReply)
	err := c.cc.Invoke(ctx, Video_ListVideos_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *videoClient) ListRelated(ctx context.Context, in *ListRelatedRequest, opts ...grpc.CallOption) (*ListVideosReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListVideosReply)
	err := c.cc.Invoke(ctx, Video_ListRelated_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *videoClient) GetVideo(ctx context.Context, in *GetVideoRequest, opts ...grpc.CallOption) (*VideoInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VideoInfo)
	err := c.cc.Invoke(ctx, Video_GetVideo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *videoClient) ListMyVideos(ctx context.Context, in *ListMyVideosRequest, opts ...grpc.CallOption) (*ListVideosReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListVideosReply)
	err := c.cc.Invoke(ctx, Video_ListMyVideos_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *videoClient) ListDanmu(ctx context.Context, in *ListDanmuRequest, opts ...grpc.CallOption) (*ListDanmuReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDanmuReply)
	err := c.cc.Invoke(ctx, Video_ListDanmu_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *videoClient) PostDanmu(ctx context.Context, in *PostDanmuRequest, opts ...grpc.CallOption) (*PostDanmuReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PostDanmuReply)
	err := c.cc.Invoke(ctx, Video_PostDanmu_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *videoClient) ListComments(ctx context.Context, in *ListCommentsRequest, opts ...grpc.CallOption) (*ListCommentsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCommentsReply)
	err := c.cc.Invoke(ctx, Video_ListComments_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *videoClient) PostComment(ctx context.Context, in *PostCommentRequest, opts ...grpc.CallOption) (*PostCommentReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PostCommentReply)
	err := c.cc.Invoke(ctx, Video_PostComment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *videoClient) ToggleLike(ctx context.Context, in *ToggleLikeRequest, opts ...grpc.CallOption) (*ToggleLikeReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ToggleLikeReply)
	err := c.cc.Invoke(ctx, Video_ToggleLike_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *videoClient) ToggleFavorite(ctx context.Context, in *ToggleFavoriteRequest, opts ...grpc.CallOption) (*ToggleFavoriteReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ToggleFavoriteReply)
	err := c.cc.Invoke(ctx, Video_ToggleFavorite_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *videoClient) GetInteractStats(ctx context.Context, in *GetInteractStatsRequest, opts ...grpc.CallOption) (*InteractStats, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InteractStats)
	err := c.cc.Invoke(ctx, Video_GetInteractStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *videoClient) ReportProcessed(ctx context.Context, in *ReportProcessedRequest, opts ...grpc.CallOption) (*ReportProcessedReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportProcessedReply)
	err := c.cc.Invoke(ctx, Video_ReportProcessed_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VideoServer is the server API for Video service.
// All implementations must embed UnimplementedVideoServer
// for forward compatibility.
type VideoServer interface {
	CreateVideo(context.Context, *CreateVideoRequest) (*CreateVideoReply, error)
	CompleteUpload(context.Context, *CompleteUploadRequest) (*CompleteUploadReply, error)
	ListVideos(context.Context, *ListVideosRequest) (*ListVideosReply, error)
	// 相关推荐:同分区按热度,排除自身(播放页侧栏)
	ListRelated(context.Context, *ListRelatedRequest) (*ListVideosReply, error)
	GetVideo(context.Context, *GetVideoRequest) (*VideoInfo, error)
	ListMyVideos(context.Context, *ListMyVideosRequest) (*ListVideosReply, error)
	// 点播历史弹幕（按播放进度 offset_ms 区间拉取）
	ListDanmu(context.Context, *ListDanmuRequest) (*ListDanmuReply, error)
	// 持久化一条点播弹幕（JWT）；实时广播仍走 comet WS
	PostDanmu(context.Context, *PostDanmuRequest) (*PostDanmuReply, error)
	// ---- 互动（M5，同库；日后可拆 interact 服务）----
	ListComments(context.Context, *ListCommentsRequest) (*ListCommentsReply, error)
	PostComment(context.Context, *PostCommentRequest) (*PostCommentReply, error)
	ToggleLike(context.Context, *ToggleLikeRequest) (*ToggleLikeReply, error)
	ToggleFavorite(context.Context, *ToggleFavoriteRequest) (*ToggleFavoriteReply, error)
	GetInteractStats(context.Context, *GetInteractStatsRequest) (*InteractStats, error)
	// 内部：media worker 转码完成后回写。videos 表归 video 服务，media 不得直写库。
	ReportProcessed(context.Context, *ReportProcessedRequest) (*ReportProcessedReply, error)
	mustEmbedUnimplementedVideoServer()
}

// UnimplementedVideoServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVideoServer struct{}

func (UnimplementedVideoServer) CreateVideo(context.Context, *CreateVideoRequest) (*CreateVideoReply, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateVideo not implemented")
}
func (UnimplementedVideoServer) CompleteUpload(context.Context, *CompleteUploadRequest) (*CompleteUploadReply, error) {
	return nil, status.Error(codes.Unimplemented, "method CompleteUpload not implemented")
}
func (UnimplementedVideoServer) ListVideos(context.Context, *ListVideosRequest) (*ListVideosReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ListVideos not implemented")
}
func (UnimplementedVideoServer) ListRelated(context.Context, *ListRelatedRequest) (*ListVideosReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ListRelated not implemented")
}
func (UnimplementedVideoServer) GetVideo(context.Context, *GetVideoRequest) (*VideoInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method GetVideo not implemented")
}
func (UnimplementedVideoServer) ListMyVideos(context.Context, *ListMyVideosRequest) (*ListVideosReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ListMyVideos not implemented")
}
func (UnimplementedVideoServer) ListDanmu(context.Context, *ListDanmuRequest) (*ListDanmuReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ListDanmu not implemented")
}
func (UnimplementedVideoServer) PostDanmu(context.Context, *PostDanmuRequest) (*PostDanmuReply, error) {
	return nil, status.Error(codes.Unimplemented, "method PostDanmu not implemented")
}
func (UnimplementedVideoServer) ListComments(context.Context, *ListCommentsRequest) (*ListCommentsReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ListComments not implemented")
}
func (UnimplementedVideoServer) PostComment(context.Context, *PostCommentRequest) (*PostCommentReply, error) {
	return nil, status.Error(codes.Unimplemented, "method PostComment not implemented")
}
func (UnimplementedVideoServer) ToggleLike(context.Context, *ToggleLikeRequest) (*ToggleLikeReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ToggleLike not implemented")
}
func (UnimplementedVideoServer) ToggleFavorite(context.Context, *ToggleFavoriteRequest) (*ToggleFavoriteReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ToggleFavorite not implemented")
}
func (UnimplementedVideoServer) GetInteractStats(context.Context, *GetInteractStatsRequest) (*InteractStats, error) {
	return nil, status.Error(codes.Unimplemented, "method GetInteractStats not implemented")
}
func (UnimplementedVideoServer) ReportProcessed(context.Context, *ReportProcessedRequest) (*ReportProcessedReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportProcessed not implemented")
}
func (UnimplementedVideoServer) mustEmbedUnimplementedVideoServer() {}
func (UnimplementedVideoServer) testEmbeddedByValue()               {}

// UnsafeVideoServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VideoServer will
// result in compilation errors.
type UnsafeVideoServer interface {
	mustEmbedUnimplementedVideoServer()
}

func RegisterVideoServer(s grpc.ServiceRegistrar, srv VideoServer) {
	// If the following call panics, it indicates UnimplementedVideoServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Video_ServiceDesc, srv)
}

func _Video_CreateVideo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateVideoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoServer).CreateVideo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Video_CreateVideo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoServer).CreateVideo(ctx, req.(*CreateVideoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Video_CompleteUpload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompleteUploadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoServer).CompleteUpload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Video_CompleteUpload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoServer).CompleteUpload(ctx, req.(*CompleteUploadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Video_ListVideos_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListVideosRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoServer).ListVideos(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Video_ListVideos_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoServer).ListVideos(ctx, req.(*ListVideosRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Video_ListRelated_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRelatedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoServer).ListRelated(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Video_ListRelated_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoServer).ListRelated(ctx, req.(*ListRelatedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Video_GetVideo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVideoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoServer).GetVideo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Video_GetVideo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoServer).GetVideo(ctx, req.(*GetVideoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Video_ListMyVideos_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMyVideosRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoServer).ListMyVideos(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Video_ListMyVideos_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoServer).ListMyVideos(ctx, req.(*ListMyVideosRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Video_ListDanmu_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDanmuRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoServer).ListDanmu(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Video_ListDanmu_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoServer).ListDanmu(ctx, req.(*ListDanmuRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Video_PostDanmu_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostDanmuRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoServer).PostDanmu(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Video_PostDanmu_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoServer).PostDanmu(ctx, req.(*PostDanmuRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Video_ListComments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCommentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoServer).ListComments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Video_ListComments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoServer).ListComments(ctx, req.(*ListCommentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Video_PostComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostCommentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoServer).PostComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Video_PostComment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoServer).PostComment(ctx, req.(*PostCommentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Video_ToggleLike_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ToggleLikeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoServer).ToggleLike(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Video_ToggleLike_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoServer).ToggleLike(ctx, req.(*ToggleLikeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Video_ToggleFavorite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ToggleFavoriteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoServer).ToggleFavorite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Video_ToggleFavorite_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoServer).ToggleFavorite(ctx, req.(*ToggleFavoriteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Video_GetInteractStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInteractStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoServer).GetInteractStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Video_GetInteractStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoServer).GetInteractStats(ctx, req.(*GetInteractStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Video_ReportProcessed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportProcessedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoServer).ReportProcessed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Video_ReportProcessed_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoServer).ReportProcessed(ctx, req.(*ReportProcessedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Video_ServiceDesc is the grpc.ServiceDesc for Video service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Video_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.video.v1.Video",
	HandlerType: (*VideoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateVideo",
			Handler:    _Video_CreateVideo_Handler,
		},
		{
			MethodName: "CompleteUpload",
			Handler:    _Video_CompleteUpload_Handler,
		},
		{
			MethodName: "ListVideos",
			Handler:    _Video_ListVideos_Handler,
		},
		{
			MethodName: "ListRelated",
			Handler:    _Video_ListRelated_Handler,
		},
		{
			MethodName: "GetVideo",
			Handler:    _Video_GetVideo_Handler,
		},
		{
			MethodName: "ListMyVideos",
			Handler:    _Video_ListMyVideos_Handler,
		},
		{
			MethodName: "ListDanmu",
			Handler:    _Video_ListDanmu_Handler,
		},
		{
			MethodName: "PostDanmu",
			Handler:    _Video_PostDanmu_Handler,
		},
		{
			MethodName: "ListComments",
			Handler:    _Video_ListComments_Handler,
		},
		{
			MethodName: "PostComment",
			Handler:    _Video_PostComment_Handler,
		},
		{
			MethodName: "ToggleLike",
			Handler:    _Video_ToggleLike_Handler,
		},
		{
			MethodName: "ToggleFavorite",
			Handler:    _Video_ToggleFavorite_Handler,
		},
		{
			MethodName: "GetInteractStats",
			Handler:    _Video_GetInteractStats_Handler,
		},
		{
			MethodName: "ReportProcessed",
			Handler:    _Video_ReportProcessed_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "video/v1/video.proto",
}
