apiVersion: v1
kind: ConfigMap
metadata:
  name: danmu-env
data:
  WS_ALLOWED_ORIGINS: {{ .Values.wsAllowedOrigins | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: danmu-secret
type: Opaque
stringData:
  DANMU_AUTH_TOKEN: {{ .Values.auth.token | quote }}
  JWT_SECRET: {{ .Values.auth.jwtSecret | quote }}
