// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.3
// source: pb/danmu.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OnMessageReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Uid           string                 `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	ClientTs      int64                  `protobuf:"varint,4,opt,name=client_ts,json=clientTs,proto3" json:"client_ts,omitempty"`
	ClientTsNano  int64                  `protobuf:"varint,5,opt,name=client_ts_nano,json=clientTsNano,proto3" json:"client_ts_nano,omitempty"`
	SourceComet   string                 `protobuf:"bytes,6,opt,name=source_comet,json=sourceComet,proto3" json:"source_comet,omitempty"`
	OffsetMs      int64                  `protobuf:"varint,7,opt,name=offset_ms,json=offsetMs,proto3" json:"offset_ms,omitempty"` // 点播播放进度（毫秒）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OnMessageReq) Reset() {
	*x = OnMessageReq{}
	mi := &file_pb_danmu_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OnMessageReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnMessageReq) ProtoMessage() {}

func (x *OnMessageReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_danmu_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnMessageReq.ProtoReflect.Descriptor instead.
func (*OnMessageReq) Descriptor() ([]byte, []int) {
	return file_pb_danmu_proto_rawDescGZIP(), []int{0}
}

func (x *OnMessageReq) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *OnMessageReq) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *OnMessageReq) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *OnMessageReq) GetClientTs() int64 {
	if x != nil {
		return x.ClientTs
	}
	return 0
}

func (x *OnMessageReq) GetClientTsNano() int64 {
	if x != nil {
		return x.ClientTsNano
	}
	return 0
}

func (x *OnMessageReq) GetSourceComet() string {
	if x != nil {
		return x.SourceComet
	}
	return ""
}

func (x *OnMessageReq) GetOffsetMs() int64 {
	if x != nil {
		return x.OffsetMs
	}
	return 0
}

type OnMessageResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MsgId         string                 `protobuf:"bytes,1,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	Filtered      string                 `protobuf:"bytes,2,opt,name=filtered,proto3" json:"filtered,omitempty"` // 过滤后的内容（含 * 打码）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OnMessageResp) Reset() {
	*x = OnMessageResp{}
	mi := &file_pb_danmu_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OnMessageResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnMessageResp) ProtoMessage() {}

func (x *OnMessageResp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_danmu_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnMessageResp.ProtoReflect.Descriptor instead.
func (*OnMessageResp) Descriptor() ([]byte, []int) {
	return file_pb_danmu_proto_rawDescGZIP(), []int{1}
}

func (x *OnMessageResp) GetMsgId() string {
	if x != nil {
		return x.MsgId
	}
	return ""
}

func (x *OnMessageResp) GetFiltered() string {
	if x != nil {
		return x.Filtered
	}
	return ""
}

type PushRoomReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"` // 已是发给客户端的最终 JSON（[]Message 数组）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushRoomReq) Reset() {
	*x = PushRoomReq{}
	mi := &file_pb_danmu_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushRoomReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushRoomReq) ProtoMessage() {}

func (x *PushRoomReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_danmu_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushRoomReq.ProtoReflect.Descriptor instead.
func (*PushRoomReq) Descriptor() ([]byte, []int) {
	return file_pb_danmu_proto_rawDescGZIP(), []int{2}
}

func (x *PushRoomReq) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *PushRoomReq) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type PushRoomResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Delivered     int32                  `protobuf:"varint,1,opt,name=delivered,proto3" json:"delivered,omitempty"` // 本机实际投递的连接数；无该房间则 0
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushRoomResp) Reset() {
	*x = PushRoomResp{}
	mi := &file_pb_danmu_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushRoomResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushRoomResp) ProtoMessage() {}

func (x *PushRoomResp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_danmu_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushRoomResp.ProtoReflect.Descriptor instead.
func (*PushRoomResp) Descriptor() ([]byte, []int) {
	return file_pb_danmu_proto_rawDescGZIP(), []int{3}
}

func (x *PushRoomResp) GetDelivered() int32 {
	if x != nil {
		return x.Delivered
	}
	return 0
}

var File_pb_danmu_proto protoreflect.FileDescriptor

const file_pb_danmu_proto_rawDesc = "" +
	"\n" +
	"\x0epb/danmu.proto\x12\x05danmu\"\xd6\x01\n" +
	"\fOnMessageReq\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x10\n" +
	"\x03uid\x18\x02 \x01(\tR\x03uid\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x1b\n" +
	"\tclient_ts\x18\x04 \x01(\x03R\bclientTs\x12$\n" +
	"\x0eclient_ts_nano\x18\x05 \x01(\x03R\fclientTsNano\x12!\n" +
	"\fsource_comet\x18\x06 \x01(\tR\vsourceComet\x12\x1b\n" +
	"\toffset_ms\x18\a \x01(\x03R\boffsetMs\"B\n" +
	"\rOnMessageResp\x12\x15\n" +
	"\x06msg_id\x18\x01 \x01(\tR\x05msgId\x12\x1a\n" +
	"\bfiltered\x18\x02 \x01(\tR\bfiltered\"@\n" +
	"\vPushRoomReq\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\",\n" +
	"\fPushRoomResp\x12\x1c\n" +
	"\tdelivered\x18\x01 \x01(\x05R\tdelivered2F\n" +
	"\fLogicService\x126\n" +
	"\tOnMessage\x12\x13.danmu.OnMessageReq\x1a\x14.danmu.OnMessageResp2C\n" +
	"\fCometService\x123\n" +
	"\bPushRoom\x12\x12.danmu.PushRoomReq\x1a\x13.danmu.PushRoomRespB\rZ\vdanmu/pb;pbb\x06proto3"

var (
	file_pb_danmu_proto_rawDescOnce sync.Once
	file_pb_danmu_proto_rawDescData []byte
)

func file_pb_danmu_proto_rawDescGZIP() []byte {
	file_pb_danmu_proto_rawDescOnce.Do(func() {
		file_pb_danmu_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_danmu_proto_rawDesc), len(file_pb_danmu_proto_rawDesc)))
	})
	return file_pb_danmu_proto_rawDescData
}

var file_pb_danmu_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_pb_danmu_proto_goTypes = []any{
	(*OnMessageReq)(nil),  // 0: danmu.OnMessageReq
	(*OnMessageResp)(nil), // 1: danmu.OnMessageResp
	(*PushRoomReq)(nil),   // 2: danmu.PushRoomReq
	(*PushRoomResp)(nil),  // 3: danmu.PushRoomResp
}
var file_pb_danmu_proto_depIdxs = []int32{
	0, // 0: danmu.LogicService.OnMessage:input_type -> danmu.OnMessageReq
	2, // 1: danmu.CometService.PushRoom:input_type -> danmu.PushRoomReq
	1, // 2: danmu.LogicService.OnMessage:output_type -> danmu.OnMessageResp
	3, // 3: danmu.CometService.PushRoom:output_type -> danmu.PushRoomResp
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pb_danmu_proto_init() }
func file_pb_danmu_proto_init() {
	if File_pb_danmu_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_danmu_proto_rawDesc), len(file_pb_danmu_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_pb_danmu_proto_goTypes,
		DependencyIndexes: file_pb_danmu_proto_depIdxs,
		MessageInfos:      file_pb_danmu_proto_msgTypes,
	}.Build()
	File_pb_danmu_proto = out.File
	file_pb_danmu_proto_goTypes = nil
	file_pb_danmu_proto_depIdxs = nil
}
