// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: pb/realtime.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RealtimeDeliveryService_PushEnvelope_FullMethodName = "/danmu.RealtimeDeliveryService/PushEnvelope"
)

// RealtimeDeliveryServiceClient is the client API for RealtimeDeliveryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// RealtimeDeliveryService is the generic Gateway-local delivery boundary for
// Phase 2/3. Cross-Gateway route lookup happens before this RPC; the selected
// Gateway then dispatches the envelope against its local Connection Kernel.
//
// The legacy CometService.PushRoom RPC remains in danmu.proto as a compatibility
// path while the distributed Job pipeline migrates incrementally.
type RealtimeDeliveryServiceClient interface {
	PushEnvelope(ctx context.Context, in *PushEnvelopeReq, opts ...grpc.CallOption) (*PushEnvelopeResp, error)
}

type realtimeDeliveryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRealtimeDeliveryServiceClient(cc grpc.ClientConnInterface) RealtimeDeliveryServiceClient {
	return &realtimeDeliveryServiceClient{cc}
}

func (c *realtimeDeliveryServiceClient) PushEnvelope(ctx context.Context, in *PushEnvelopeReq, opts ...grpc.CallOption) (*PushEnvelopeResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PushEnvelopeResp)
	err := c.cc.Invoke(ctx, RealtimeDeliveryService_PushEnvelope_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RealtimeDeliveryServiceServer is the server API for RealtimeDeliveryService service.
// All implementations must embed UnimplementedRealtimeDeliveryServiceServer
// for forward compatibility.
//
// RealtimeDeliveryService is the generic Gateway-local delivery boundary for
// Phase 2/3. Cross-Gateway route lookup happens before this RPC; the selected
// Gateway then dispatches the envelope against its local Connection Kernel.
//
// The legacy CometService.PushRoom RPC remains in danmu.proto as a compatibility
// path while the distributed Job pipeline migrates incrementally.
type RealtimeDeliveryServiceServer interface {
	PushEnvelope(context.Context, *PushEnvelopeReq) (*PushEnvelopeResp, error)
	mustEmbedUnimplementedRealtimeDeliveryServiceServer()
}

// UnimplementedRealtimeDeliveryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRealtimeDeliveryServiceServer struct{}

func (UnimplementedRealtimeDeliveryServiceServer) PushEnvelope(context.Context, *PushEnvelopeReq) (*PushEnvelopeResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PushEnvelope not implemented")
}
func (UnimplementedRealtimeDeliveryServiceServer) mustEmbedUnimplementedRealtimeDeliveryServiceServer() {
}
func (UnimplementedRealtimeDeliveryServiceServer) testEmbeddedByValue() {}

// UnsafeRealtimeDeliveryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RealtimeDeliveryServiceServer will
// result in compilation errors.
type UnsafeRealtimeDeliveryServiceServer interface {
	mustEmbedUnimplementedRealtimeDeliveryServiceServer()
}

func RegisterRealtimeDeliveryServiceServer(s grpc.ServiceRegistrar, srv RealtimeDeliveryServiceServer) {
	// If the following call pancis, it indicates UnimplementedRealtimeDeliveryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RealtimeDeliveryService_ServiceDesc, srv)
}

func _RealtimeDeliveryService_PushEnvelope_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PushEnvelopeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RealtimeDeliveryServiceServer).PushEnvelope(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RealtimeDeliveryService_PushEnvelope_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RealtimeDeliveryServiceServer).PushEnvelope(ctx, req.(*PushEnvelopeReq))
	}
	return interceptor(ctx, in, info, handler)
}

// RealtimeDeliveryService_ServiceDesc is the grpc.ServiceDesc for RealtimeDeliveryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RealtimeDeliveryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "danmu.RealtimeDeliveryService",
	HandlerType: (*RealtimeDeliveryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PushEnvelope",
			Handler:    _RealtimeDeliveryService_PushEnvelope_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/realtime.proto",
}
