// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: pb/realtime.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TargetType int32

const (
	TargetType_TARGET_TYPE_UNSPECIFIED TargetType = 0
	TargetType_TARGET_USER             TargetType = 1
	TargetType_TARGET_DEVICE           TargetType = 2
	TargetType_TARGET_CHANNEL          TargetType = 3
	TargetType_TARGET_BROADCAST        TargetType = 4
)

// Enum value maps for TargetType.
var (
	TargetType_name = map[int32]string{
		0: "TARGET_TYPE_UNSPECIFIED",
		1: "TARGET_USER",
		2: "TARGET_DEVICE",
		3: "TARGET_CHANNEL",
		4: "TARGET_BROADCAST",
	}
	TargetType_value = map[string]int32{
		"TARGET_TYPE_UNSPECIFIED": 0,
		"TARGET_USER":             1,
		"TARGET_DEVICE":           2,
		"TARGET_CHANNEL":          3,
		"TARGET_BROADCAST":        4,
	}
)

func (x TargetType) Enum() *TargetType {
	p := new(TargetType)
	*p = x
	return p
}

func (x TargetType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TargetType) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_realtime_proto_enumTypes[0].Descriptor()
}

func (TargetType) Type() protoreflect.EnumType {
	return &file_pb_realtime_proto_enumTypes[0]
}

func (x TargetType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TargetType.Descriptor instead.
func (TargetType) EnumDescriptor() ([]byte, []int) {
	return file_pb_realtime_proto_rawDescGZIP(), []int{0}
}

type DeliveryClass int32

const (
	DeliveryClass_DELIVERY_CLASS_UNSPECIFIED DeliveryClass = 0
	DeliveryClass_DELIVERY_EPHEMERAL         DeliveryClass = 1
	// Schema value only in Phase 2. It does not imply durable persistence,
	// idempotency, sequencing, offline sync or client ACK until Phase 4 exists.
	DeliveryClass_DELIVERY_RELIABLE DeliveryClass = 2
)

// Enum value maps for DeliveryClass.
var (
	DeliveryClass_name = map[int32]string{
		0: "DELIVERY_CLASS_UNSPECIFIED",
		1: "DELIVERY_EPHEMERAL",
		2: "DELIVERY_RELIABLE",
	}
	DeliveryClass_value = map[string]int32{
		"DELIVERY_CLASS_UNSPECIFIED": 0,
		"DELIVERY_EPHEMERAL":         1,
		"DELIVERY_RELIABLE":          2,
	}
)

func (x DeliveryClass) Enum() *DeliveryClass {
	p := new(DeliveryClass)
	*p = x
	return p
}

func (x DeliveryClass) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeliveryClass) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_realtime_proto_enumTypes[1].Descriptor()
}

func (DeliveryClass) Type() protoreflect.EnumType {
	return &file_pb_realtime_proto_enumTypes[1]
}

func (x DeliveryClass) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeliveryClass.Descriptor instead.
func (DeliveryClass) EnumDescriptor() ([]byte, []int) {
	return file_pb_realtime_proto_rawDescGZIP(), []int{1}
}

type DeliveryEnvelope struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	MessageId       string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	ClientMessageId string                 `protobuf:"bytes,2,opt,name=client_message_id,json=clientMessageId,proto3" json:"client_message_id,omitempty"`
	SenderId        string                 `protobuf:"bytes,3,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	TargetType      TargetType             `protobuf:"varint,4,opt,name=target_type,json=targetType,proto3,enum=danmu.TargetType" json:"target_type,omitempty"`
	// USER: user id; DEVICE: device id; CHANNEL: channel id; BROADCAST: empty.
	TargetId string `protobuf:"bytes,5,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	// DEVICE target only. Device IDs are scoped by user in SessionIndex.
	TargetUserId  string        `protobuf:"bytes,6,opt,name=target_user_id,json=targetUserId,proto3" json:"target_user_id,omitempty"`
	DeliveryClass DeliveryClass `protobuf:"varint,7,opt,name=delivery_class,json=deliveryClass,proto3,enum=danmu.DeliveryClass" json:"delivery_class,omitempty"`
	MessageType   string        `protobuf:"bytes,8,opt,name=message_type,json=messageType,proto3" json:"message_type,omitempty"`
	Sequence      int64         `protobuf:"varint,9,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Payload       []byte        `protobuf:"bytes,10,opt,name=payload,proto3" json:"payload,omitempty"`
	ClientTs      int64         `protobuf:"varint,11,opt,name=client_ts,json=clientTs,proto3" json:"client_ts,omitempty"`
	ServerTs      int64         `protobuf:"varint,12,opt,name=server_ts,json=serverTs,proto3" json:"server_ts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeliveryEnvelope) Reset() {
	*x = DeliveryEnvelope{}
	mi := &file_pb_realtime_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeliveryEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliveryEnvelope) ProtoMessage() {}

func (x *DeliveryEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_pb_realtime_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliveryEnvelope.ProtoReflect.Descriptor instead.
func (*DeliveryEnvelope) Descriptor() ([]byte, []int) {
	return file_pb_realtime_proto_rawDescGZIP(), []int{0}
}

func (x *DeliveryEnvelope) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *DeliveryEnvelope) GetClientMessageId() string {
	if x != nil {
		return x.ClientMessageId
	}
	return ""
}

func (x *DeliveryEnvelope) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *DeliveryEnvelope) GetTargetType() TargetType {
	if x != nil {
		return x.TargetType
	}
	return TargetType_TARGET_TYPE_UNSPECIFIED
}

func (x *DeliveryEnvelope) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

func (x *DeliveryEnvelope) GetTargetUserId() string {
	if x != nil {
		return x.TargetUserId
	}
	return ""
}

func (x *DeliveryEnvelope) GetDeliveryClass() DeliveryClass {
	if x != nil {
		return x.DeliveryClass
	}
	return DeliveryClass_DELIVERY_CLASS_UNSPECIFIED
}

func (x *DeliveryEnvelope) GetMessageType() string {
	if x != nil {
		return x.MessageType
	}
	return ""
}

func (x *DeliveryEnvelope) GetSequence() int64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *DeliveryEnvelope) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *DeliveryEnvelope) GetClientTs() int64 {
	if x != nil {
		return x.ClientTs
	}
	return 0
}

func (x *DeliveryEnvelope) GetServerTs() int64 {
	if x != nil {
		return x.ServerTs
	}
	return 0
}

type PushEnvelopeReq struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Envelope *DeliveryEnvelope      `protobuf:"bytes,1,opt,name=envelope,proto3" json:"envelope,omitempty"`
	// Final bytes for the current WebSocket client. This intentionally remains
	// separate from envelope.payload during migration because legacy Danmu uses
	// an existing []Message JSON wire representation.
	ClientPayload []byte `protobuf:"bytes,2,opt,name=client_payload,json=clientPayload,proto3" json:"client_payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushEnvelopeReq) Reset() {
	*x = PushEnvelopeReq{}
	mi := &file_pb_realtime_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushEnvelopeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushEnvelopeReq) ProtoMessage() {}

func (x *PushEnvelopeReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_realtime_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushEnvelopeReq.ProtoReflect.Descriptor instead.
func (*PushEnvelopeReq) Descriptor() ([]byte, []int) {
	return file_pb_realtime_proto_rawDescGZIP(), []int{1}
}

func (x *PushEnvelopeReq) GetEnvelope() *DeliveryEnvelope {
	if x != nil {
		return x.Envelope
	}
	return nil
}

func (x *PushEnvelopeReq) GetClientPayload() []byte {
	if x != nil {
		return x.ClientPayload
	}
	return nil
}

type PushEnvelopeResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Delivered     int32                  `protobuf:"varint,1,opt,name=delivered,proto3" json:"delivered,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushEnvelopeResp) Reset() {
	*x = PushEnvelopeResp{}
	mi := &file_pb_realtime_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushEnvelopeResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushEnvelopeResp) ProtoMessage() {}

func (x *PushEnvelopeResp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_realtime_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushEnvelopeResp.ProtoReflect.Descriptor instead.
func (*PushEnvelopeResp) Descriptor() ([]byte, []int) {
	return file_pb_realtime_proto_rawDescGZIP(), []int{2}
}

func (x *PushEnvelopeResp) GetDelivered() int32 {
	if x != nil {
		return x.Delivered
	}
	return 0
}

var File_pb_realtime_proto protoreflect.FileDescriptor

const file_pb_realtime_proto_rawDesc = "" +
	"\n" +
	"\x11pb/realtime.proto\x12\x05danmu\"\xc1\x03\n" +
	"\x10DeliveryEnvelope\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12*\n" +
	"\x11client_message_id\x18\x02 \x01(\tR\x0fclientMessageId\x12\x1b\n" +
	"\tsender_id\x18\x03 \x01(\tR\bsenderId\x122\n" +
	"\vtarget_type\x18\x04 \x01(\x0e2\x11.danmu.TargetTypeR\n" +
	"targetType\x12\x1b\n" +
	"\ttarget_id\x18\x05 \x01(\tR\btargetId\x12$\n" +
	"\x0etarget_user_id\x18\x06 \x01(\tR\ftargetUserId\x12;\n" +
	"\x0edelivery_class\x18\a \x01(\x0e2\x14.danmu.DeliveryClassR\rdeliveryClass\x12!\n" +
	"\fmessage_type\x18\b \x01(\tR\vmessageType\x12\x1a\n" +
	"\bsequence\x18\t \x01(\x03R\bsequence\x12\x18\n" +
	"\apayload\x18\n" +
	" \x01(\fR\apayload\x12\x1b\n" +
	"\tclient_ts\x18\v \x01(\x03R\bclientTs\x12\x1b\n" +
	"\tserver_ts\x18\f \x01(\x03R\bserverTs\"m\n" +
	"\x0fPushEnvelopeReq\x123\n" +
	"\benvelope\x18\x01 \x01(\v2\x17.danmu.DeliveryEnvelopeR\benvelope\x12%\n" +
	"\x0eclient_payload\x18\x02 \x01(\fR\rclientPayload\"0\n" +
	"\x10PushEnvelopeResp\x12\x1c\n" +
	"\tdelivered\x18\x01 \x01(\x05R\tdelivered*w\n" +
	"\n" +
	"TargetType\x12\x1b\n" +
	"\x17TARGET_TYPE_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vTARGET_USER\x10\x01\x12\x11\n" +
	"\rTARGET_DEVICE\x10\x02\x12\x12\n" +
	"\x0eTARGET_CHANNEL\x10\x03\x12\x14\n" +
	"\x10TARGET_BROADCAST\x10\x04*^\n" +
	"\rDeliveryClass\x12\x1e\n" +
	"\x1aDELIVERY_CLASS_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12DELIVERY_EPHEMERAL\x10\x01\x12\x15\n" +
	"\x11DELIVERY_RELIABLE\x10\x022Z\n" +
	"\x17RealtimeDeliveryService\x12?\n" +
	"\fPushEnvelope\x12\x16.danmu.PushEnvelopeReq\x1a\x17.danmu.PushEnvelopeRespB/Z-github.com/YansIlinta/danmu-distributed/pb;pbb\x06proto3"

var (
	file_pb_realtime_proto_rawDescOnce sync.Once
	file_pb_realtime_proto_rawDescData []byte
)

func file_pb_realtime_proto_rawDescGZIP() []byte {
	file_pb_realtime_proto_rawDescOnce.Do(func() {
		file_pb_realtime_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_realtime_proto_rawDesc), len(file_pb_realtime_proto_rawDesc)))
	})
	return file_pb_realtime_proto_rawDescData
}

var file_pb_realtime_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_pb_realtime_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_pb_realtime_proto_goTypes = []any{
	(TargetType)(0),          // 0: danmu.TargetType
	(DeliveryClass)(0),       // 1: danmu.DeliveryClass
	(*DeliveryEnvelope)(nil), // 2: danmu.DeliveryEnvelope
	(*PushEnvelopeReq)(nil),  // 3: danmu.PushEnvelopeReq
	(*PushEnvelopeResp)(nil), // 4: danmu.PushEnvelopeResp
}
var file_pb_realtime_proto_depIdxs = []int32{
	0, // 0: danmu.DeliveryEnvelope.target_type:type_name -> danmu.TargetType
	1, // 1: danmu.DeliveryEnvelope.delivery_class:type_name -> danmu.DeliveryClass
	2, // 2: danmu.PushEnvelopeReq.envelope:type_name -> danmu.DeliveryEnvelope
	3, // 3: danmu.RealtimeDeliveryService.PushEnvelope:input_type -> danmu.PushEnvelopeReq
	4, // 4: danmu.RealtimeDeliveryService.PushEnvelope:output_type -> danmu.PushEnvelopeResp
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_pb_realtime_proto_init() }
func file_pb_realtime_proto_init() {
	if File_pb_realtime_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_realtime_proto_rawDesc), len(file_pb_realtime_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_realtime_proto_goTypes,
		DependencyIndexes: file_pb_realtime_proto_depIdxs,
		EnumInfos:         file_pb_realtime_proto_enumTypes,
		MessageInfos:      file_pb_realtime_proto_msgTypes,
	}.Build()
	File_pb_realtime_proto = out.File
	file_pb_realtime_proto_goTypes = nil
	file_pb_realtime_proto_depIdxs = nil
}
