// X-Plore 社交关系服务契约:关注/粉丝 + UP 主公开信息。
// 用户名等基础信息经 gRPC 调 user 服务,本服务只落关注关系(user_follows)。

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: social/v1/social.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ToggleFollowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"` // 被关注人
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToggleFollowRequest) Reset() {
	*x = ToggleFollowRequest{}
	mi := &file_social_v1_social_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToggleFollowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToggleFollowRequest) ProtoMessage() {}

func (x *ToggleFollowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_social_v1_social_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToggleFollowRequest.ProtoReflect.Descriptor instead.
func (*ToggleFollowRequest) Descriptor() ([]byte, []int) {
	return file_social_v1_social_proto_rawDescGZIP(), []int{0}
}

func (x *ToggleFollowRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ToggleFollowReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Following     bool                   `protobuf:"varint,1,opt,name=following,proto3" json:"following,omitempty"`
	FollowerCount int64                  `protobuf:"varint,2,opt,name=follower_count,json=followerCount,proto3" json:"follower_count,omitempty"` // 被关注人最新粉丝数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToggleFollowReply) Reset() {
	*x = ToggleFollowReply{}
	mi := &file_social_v1_social_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToggleFollowReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToggleFollowReply) ProtoMessage() {}

func (x *ToggleFollowReply) ProtoReflect() protoreflect.Message {
	mi := &file_social_v1_social_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToggleFollowReply.ProtoReflect.Descriptor instead.
func (*ToggleFollowReply) Descriptor() ([]byte, []int) {
	return file_social_v1_social_proto_rawDescGZIP(), []int{1}
}

func (x *ToggleFollowReply) GetFollowing() bool {
	if x != nil {
		return x.Following
	}
	return false
}

func (x *ToggleFollowReply) GetFollowerCount() int64 {
	if x != nil {
		return x.FollowerCount
	}
	return 0
}

type GetProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfileRequest) Reset() {
	*x = GetProfileRequest{}
	mi := &file_social_v1_social_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileRequest) ProtoMessage() {}

func (x *GetProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_social_v1_social_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileRequest.ProtoReflect.Descriptor instead.
func (*GetProfileRequest) Descriptor() ([]byte, []int) {
	return file_social_v1_social_proto_rawDescGZIP(), []int{2}
}

func (x *GetProfileRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type Profile struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Username       string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	FollowerCount  int64                  `protobuf:"varint,3,opt,name=follower_count,json=followerCount,proto3" json:"follower_count,omitempty"`
	FollowingCount int64                  `protobuf:"varint,4,opt,name=following_count,json=followingCount,proto3" json:"following_count,omitempty"`
	Following      bool                   `protobuf:"varint,5,opt,name=following,proto3" json:"following,omitempty"` // 当前用户是否已关注(未登录 false)
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Profile) Reset() {
	*x = Profile{}
	mi := &file_social_v1_social_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Profile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Profile) ProtoMessage() {}

func (x *Profile) ProtoReflect() protoreflect.Message {
	mi := &file_social_v1_social_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Profile.ProtoReflect.Descriptor instead.
func (*Profile) Descriptor() ([]byte, []int) {
	return file_social_v1_social_proto_rawDescGZIP(), []int{3}
}

func (x *Profile) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Profile) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Profile) GetFollowerCount() int64 {
	if x != nil {
		return x.FollowerCount
	}
	return 0
}

func (x *Profile) GetFollowingCount() int64 {
	if x != nil {
		return x.FollowingCount
	}
	return 0
}

func (x *Profile) GetFollowing() bool {
	if x != nil {
		return x.Following
	}
	return false
}

type ListFollowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Size          int32                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFollowRequest) Reset() {
	*x = ListFollowRequest{}
	mi := &file_social_v1_social_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFollowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFollowRequest) ProtoMessage() {}

func (x *ListFollowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_social_v1_social_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFollowRequest.ProtoReflect.Descriptor instead.
func (*ListFollowRequest) Descriptor() ([]byte, []int) {
	return file_social_v1_social_proto_rawDescGZIP(), []int{4}
}

func (x *ListFollowRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ListFollowRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListFollowRequest) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type FollowUser struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // 关注时间 unix ms
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FollowUser) Reset() {
	*x = FollowUser{}
	mi := &file_social_v1_social_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FollowUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowUser) ProtoMessage() {}

func (x *FollowUser) ProtoReflect() protoreflect.Message {
	mi := &file_social_v1_social_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowUser.ProtoReflect.Descriptor instead.
func (*FollowUser) Descriptor() ([]byte, []int) {
	return file_social_v1_social_proto_rawDescGZIP(), []int{5}
}

func (x *FollowUser) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *FollowUser) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *FollowUser) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type ListFollowReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*FollowUser          `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFollowReply) Reset() {
	*x = ListFollowReply{}
	mi := &file_social_v1_social_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFollowReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFollowReply) ProtoMessage() {}

func (x *ListFollowReply) ProtoReflect() protoreflect.Message {
	mi := &file_social_v1_social_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFollowReply.ProtoReflect.Descriptor instead.
func (*ListFollowReply) Descriptor() ([]byte, []int) {
	return file_social_v1_social_proto_rawDescGZIP(), []int{6}
}

func (x *ListFollowReply) GetList() []*FollowUser {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *ListFollowReply) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_social_v1_social_proto protoreflect.FileDescriptor

const file_social_v1_social_proto_rawDesc = "" +
	"\n" +
	"\x16social/v1/social.proto\x12\rapi.social.v1\x1a\x1cgoogle/api/annotations.proto\"%\n" +
	"\x13ToggleFollowRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"X\n" +
	"\x11ToggleFollowReply\x12\x1c\n" +
	"\tfollowing\x18\x01 \x01(\bR\tfollowing\x12%\n" +
	"\x0efollower_count\x18\x02 \x01(\x03R\rfollowerCount\"#\n" +
	"\x11GetProfileRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"\xa3\x01\n" +
	"\aProfile\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12%\n" +
	"\x0efollower_count\x18\x03 \x01(\x03R\rfollowerCount\x12'\n" +
	"\x0ffollowing_count\x18\x04 \x01(\x03R\x0efollowingCount\x12\x1c\n" +
	"\tfollowing\x18\x05 \x01(\bR\tfollowing\"K\n" +
	"\x11ListFollowRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x05R\x04size\"W\n" +
	"\n" +
	"FollowUser\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1d\n" +
	"\n" +
	"created_at\x18\x03 \x01(\x03R\tcreatedAt\"V\n" +
	"\x0fListFollowReply\x12-\n" +
	"\x04list\x18\x01 \x03(\v2\x19.api.social.v1.FollowUserR\x04list\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total2\xd4\x03\n" +
	"\x06Social\x12v\n" +
	"\fToggleFollow\x12\".api.social.v1.ToggleFollowRequest\x1a .api.social.v1.ToggleFollowReply\" \x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/v1/users/{id}/follow\x12f\n" +
	"\n" +
	"GetProfile\x12 .api.social.v1.GetProfileRequest\x1a\x16.api.social.v1.Profile\"\x1e\x82\xd3\xe4\x93\x02\x18\x12\x16/v1/users/{id}/profile\x12u\n" +
	"\x0eListFollowings\x12 .api.social.v1.ListFollowRequest\x1a\x1e.api.social.v1.ListFollowReply\"!\x82\xd3\xe4\x93\x02\x1b\x12\x19/v1/users/{id}/followings\x12s\n" +
	"\rListFollowers\x12 .api.social.v1.ListFollowRequest\x1a\x1e.api.social.v1.ListFollowReply\" \x82\xd3\xe4\x93\x02\x1a\x12\x18/v1/users/{id}/followersB6Z4github.com/YansIlinta/wavehub-micro/api/social/v1;v1b\x06proto3"

var (
	file_social_v1_social_proto_rawDescOnce sync.Once
	file_social_v1_social_proto_rawDescData []byte
)

func file_social_v1_social_proto_rawDescGZIP() []byte {
	file_social_v1_social_proto_rawDescOnce.Do(func() {
		file_social_v1_social_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_social_v1_social_proto_rawDesc), len(file_social_v1_social_proto_rawDesc)))
	})
	return file_social_v1_social_proto_rawDescData
}

var file_social_v1_social_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_social_v1_social_proto_goTypes = []any{
	(*ToggleFollowRequest)(nil), // 0: api.social.v1.ToggleFollowRequest
	(*ToggleFollowReply)(nil),   // 1: api.social.v1.ToggleFollowReply
	(*GetProfileRequest)(nil),   // 2: api.social.v1.GetProfileRequest
	(*Profile)(nil),             // 3: api.social.v1.Profile
	(*ListFollowRequest)(nil),   // 4: api.social.v1.ListFollowRequest
	(*FollowUser)(nil),          // 5: api.social.v1.FollowUser
	(*ListFollowReply)(nil),     // 6: api.social.v1.ListFollowReply
}
var file_social_v1_social_proto_depIdxs = []int32{
	5, // 0: api.social.v1.ListFollowReply.list:type_name -> api.social.v1.FollowUser
	0, // 1: api.social.v1.Social.ToggleFollow:input_type -> api.social.v1.ToggleFollowRequest
	2, // 2: api.social.v1.Social.GetProfile:input_type -> api.social.v1.GetProfileRequest
	4, // 3: api.social.v1.Social.ListFollowings:input_type -> api.social.v1.ListFollowRequest
	4, // 4: api.social.v1.Social.ListFollowers:input_type -> api.social.v1.ListFollowRequest
	1, // 5: api.social.v1.Social.ToggleFollow:output_type -> api.social.v1.ToggleFollowReply
	3, // 6: api.social.v1.Social.GetProfile:output_type -> api.social.v1.Profile
	6, // 7: api.social.v1.Social.ListFollowings:output_type -> api.social.v1.ListFollowReply
	6, // 8: api.social.v1.Social.ListFollowers:output_type -> api.social.v1.ListFollowReply
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_social_v1_social_proto_init() }
func file_social_v1_social_proto_init() {
	if File_social_v1_social_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_social_v1_social_proto_rawDesc), len(file_social_v1_social_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_social_v1_social_proto_goTypes,
		DependencyIndexes: file_social_v1_social_proto_depIdxs,
		MessageInfos:      file_social_v1_social_proto_msgTypes,
	}.Build()
	File_social_v1_social_proto = out.File
	file_social_v1_social_proto_goTypes = nil
	file_social_v1_social_proto_depIdxs = nil
}
