// X-Plore 社交关系服务契约:关注/粉丝 + UP 主公开信息。
// 用户名等基础信息经 gRPC 调 user 服务,本服务只落关注关系(user_follows)。

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: social/v1/social.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Social_ToggleFollow_FullMethodName   = "/api.social.v1.Social/ToggleFollow"
	Social_GetProfile_FullMethodName     = "/api.social.v1.Social/GetProfile"
	Social_ListFollowings_FullMethodName = "/api.social.v1.Social/ListFollowings"
	Social_ListFollowers_FullMethodName  = "/api.social.v1.Social/ListFollowers"
)

// SocialClient is the client API for Social service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SocialClient interface {
	// toggle 关注(JWT);不能关注自己
	ToggleFollow(ctx context.Context, in *ToggleFollowRequest, opts ...grpc.CallOption) (*ToggleFollowReply, error)
	// UP 主公开信息;带 token 时返回当前用户是否已关注
	GetProfile(ctx context.Context, in *GetProfileRequest, opts ...grpc.CallOption) (*Profile, error)
	ListFollowings(ctx context.Context, in *ListFollowRequest, opts ...grpc.CallOption) (*ListFollowReply, error)
	ListFollowers(ctx context.Context, in *ListFollowRequest, opts ...grpc.CallOption) (*ListFollowReply, error)
}

type socialClient struct {
	cc grpc.ClientConnInterface
}

func NewSocialClient(cc grpc.ClientConnInterface) SocialClient {
	return &socialClient{cc}
}

func (c *socialClient) ToggleFollow(ctx context.Context, in *ToggleFollowRequest, opts ...grpc.CallOption) (*ToggleFollowReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ToggleFollowReply)
	err := c.cc.Invoke(ctx, Social_ToggleFollow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialClient) GetProfile(ctx context.Context, in *GetProfileRequest, opts ...grpc.CallOption) (*Profile, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Profile)
	err := c.cc.Invoke(ctx, Social_GetProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialClient) ListFollowings(ctx context.Context, in *ListFollowRequest, opts ...grpc.CallOption) (*ListFollowReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListFollowReply)
	err := c.cc.Invoke(ctx, Social_ListFollowings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialClient) ListFollowers(ctx context.Context, in *ListFollowRequest, opts ...grpc.CallOption) (*ListFollowReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListFollowReply)
	err := c.cc.Invoke(ctx, Social_ListFollowers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SocialServer is the server API for Social service.
// All implementations must embed UnimplementedSocialServer
// for forward compatibility.
type SocialServer interface {
	// toggle 关注(JWT);不能关注自己
	ToggleFollow(context.Context, *ToggleFollowRequest) (*ToggleFollowReply, error)
	// UP 主公开信息;带 token 时返回当前用户是否已关注
	GetProfile(context.Context, *GetProfileRequest) (*Profile, error)
	ListFollowings(context.Context, *ListFollowRequest) (*ListFollowReply, error)
	ListFollowers(context.Context, *ListFollowRequest) (*ListFollowReply, error)
	mustEmbedUnimplementedSocialServer()
}

// UnimplementedSocialServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSocialServer struct{}

func (UnimplementedSocialServer) ToggleFollow(context.Context, *ToggleFollowRequest) (*ToggleFollowReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ToggleFollow not implemented")
}
func (UnimplementedSocialServer) GetProfile(context.Context, *GetProfileRequest) (*Profile, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProfile not implemented")
}
func (UnimplementedSocialServer) ListFollowings(context.Context, *ListFollowRequest) (*ListFollowReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ListFollowings not implemented")
}
func (UnimplementedSocialServer) ListFollowers(context.Context, *ListFollowRequest) (*ListFollowReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ListFollowers not implemented")
}
func (UnimplementedSocialServer) mustEmbedUnimplementedSocialServer() {}
func (UnimplementedSocialServer) testEmbeddedByValue()                {}

// UnsafeSocialServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SocialServer will
// result in compilation errors.
type UnsafeSocialServer interface {
	mustEmbedUnimplementedSocialServer()
}

func RegisterSocialServer(s grpc.ServiceRegistrar, srv SocialServer) {
	// If the following call panics, it indicates UnimplementedSocialServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Social_ServiceDesc, srv)
}

func _Social_ToggleFollow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ToggleFollowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServer).ToggleFollow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Social_ToggleFollow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServer).ToggleFollow(ctx, req.(*ToggleFollowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Social_GetProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServer).GetProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Social_GetProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServer).GetProfile(ctx, req.(*GetProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Social_ListFollowings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFollowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServer).ListFollowings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Social_ListFollowings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServer).ListFollowings(ctx, req.(*ListFollowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Social_ListFollowers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFollowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServer).ListFollowers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Social_ListFollowers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServer).ListFollowers(ctx, req.(*ListFollowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Social_ServiceDesc is the grpc.ServiceDesc for Social service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Social_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.social.v1.Social",
	HandlerType: (*SocialServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ToggleFollow",
			Handler:    _Social_ToggleFollow_Handler,
		},
		{
			MethodName: "GetProfile",
			Handler:    _Social_GetProfile_Handler,
		},
		{
			MethodName: "ListFollowings",
			Handler:    _Social_ListFollowings_Handler,
		},
		{
			MethodName: "ListFollowers",
			Handler:    _Social_ListFollowers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "social/v1/social.proto",
}
