// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             (unknown)
// source: social/v1/social.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationSocialGetProfile = "/api.social.v1.Social/GetProfile"
const OperationSocialListFollowers = "/api.social.v1.Social/ListFollowers"
const OperationSocialListFollowings = "/api.social.v1.Social/ListFollowings"
const OperationSocialToggleFollow = "/api.social.v1.Social/ToggleFollow"

type SocialHTTPServer interface {
	// GetProfile UP 主公开信息;带 token 时返回当前用户是否已关注
	GetProfile(context.Context, *GetProfileRequest) (*Profile, error)
	ListFollowers(context.Context, *ListFollowRequest) (*ListFollowReply, error)
	ListFollowings(context.Context, *ListFollowRequest) (*ListFollowReply, error)
	// ToggleFollow toggle 关注(JWT);不能关注自己
	ToggleFollow(context.Context, *ToggleFollowRequest) (*ToggleFollowReply, error)
}

func RegisterSocialHTTPServer(s *http.Server, srv SocialHTTPServer) {
	r := s.Route("/")
	r.POST("/v1/users/{id}/follow", _Social_ToggleFollow0_HTTP_Handler(srv))
	r.GET("/v1/users/{id}/profile", _Social_GetProfile0_HTTP_Handler(srv))
	r.GET("/v1/users/{id}/followings", _Social_ListFollowings0_HTTP_Handler(srv))
	r.GET("/v1/users/{id}/followers", _Social_ListFollowers0_HTTP_Handler(srv))
}

func _Social_ToggleFollow0_HTTP_Handler(srv SocialHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ToggleFollowRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSocialToggleFollow)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ToggleFollow(ctx, req.(*ToggleFollowRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ToggleFollowReply)
		return ctx.Result(200, reply)
	}
}

func _Social_GetProfile0_HTTP_Handler(srv SocialHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetProfileRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSocialGetProfile)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetProfile(ctx, req.(*GetProfileRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Profile)
		return ctx.Result(200, reply)
	}
}

func _Social_ListFollowings0_HTTP_Handler(srv SocialHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListFollowRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSocialListFollowings)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListFollowings(ctx, req.(*ListFollowRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListFollowReply)
		return ctx.Result(200, reply)
	}
}

func _Social_ListFollowers0_HTTP_Handler(srv SocialHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListFollowRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSocialListFollowers)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListFollowers(ctx, req.(*ListFollowRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListFollowReply)
		return ctx.Result(200, reply)
	}
}

type SocialHTTPClient interface {
	// GetProfile UP 主公开信息;带 token 时返回当前用户是否已关注
	GetProfile(ctx context.Context, req *GetProfileRequest, opts ...http.CallOption) (rsp *Profile, err error)
	ListFollowers(ctx context.Context, req *ListFollowRequest, opts ...http.CallOption) (rsp *ListFollowReply, err error)
	ListFollowings(ctx context.Context, req *ListFollowRequest, opts ...http.CallOption) (rsp *ListFollowReply, err error)
	// ToggleFollow toggle 关注(JWT);不能关注自己
	ToggleFollow(ctx context.Context, req *ToggleFollowRequest, opts ...http.CallOption) (rsp *ToggleFollowReply, err error)
}

type SocialHTTPClientImpl struct {
	cc *http.Client
}

func NewSocialHTTPClient(client *http.Client) SocialHTTPClient {
	return &SocialHTTPClientImpl{client}
}

// GetProfile UP 主公开信息;带 token 时返回当前用户是否已关注
func (c *SocialHTTPClientImpl) GetProfile(ctx context.Context, in *GetProfileRequest, opts ...http.CallOption) (*Profile, error) {
	var out Profile
	pattern := "/v1/users/{id}/profile"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationSocialGetProfile))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *SocialHTTPClientImpl) ListFollowers(ctx context.Context, in *ListFollowRequest, opts ...http.CallOption) (*ListFollowReply, error) {
	var out ListFollowReply
	pattern := "/v1/users/{id}/followers"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationSocialListFollowers))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *SocialHTTPClientImpl) ListFollowings(ctx context.Context, in *ListFollowRequest, opts ...http.CallOption) (*ListFollowReply, error) {
	var out ListFollowReply
	pattern := "/v1/users/{id}/followings"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationSocialListFollowings))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ToggleFollow toggle 关注(JWT);不能关注自己
func (c *SocialHTTPClientImpl) ToggleFollow(ctx context.Context, in *ToggleFollowRequest, opts ...http.CallOption) (*ToggleFollowReply, error) {
	var out ToggleFollowReply
	pattern := "/v1/users/{id}/follow"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationSocialToggleFollow))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
