// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v4.25.3
// source: pb/danmu.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LogicService_OnMessage_FullMethodName = "/danmu.LogicService/OnMessage"
)

// LogicServiceClient is the client API for LogicService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// LogicService: Comet 把上行弹幕转发给 Logic 做过滤/生成 msg_id/写 Kafka。
type LogicServiceClient interface {
	OnMessage(ctx context.Context, in *OnMessageReq, opts ...grpc.CallOption) (*OnMessageResp, error)
}

type logicServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLogicServiceClient(cc grpc.ClientConnInterface) LogicServiceClient {
	return &logicServiceClient{cc}
}

func (c *logicServiceClient) OnMessage(ctx context.Context, in *OnMessageReq, opts ...grpc.CallOption) (*OnMessageResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OnMessageResp)
	err := c.cc.Invoke(ctx, LogicService_OnMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LogicServiceServer is the server API for LogicService service.
// All implementations must embed UnimplementedLogicServiceServer
// for forward compatibility.
//
// LogicService: Comet 把上行弹幕转发给 Logic 做过滤/生成 msg_id/写 Kafka。
type LogicServiceServer interface {
	OnMessage(context.Context, *OnMessageReq) (*OnMessageResp, error)
	mustEmbedUnimplementedLogicServiceServer()
}

// UnimplementedLogicServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLogicServiceServer struct{}

func (UnimplementedLogicServiceServer) OnMessage(context.Context, *OnMessageReq) (*OnMessageResp, error) {
	return nil, status.Error(codes.Unimplemented, "method OnMessage not implemented")
}
func (UnimplementedLogicServiceServer) mustEmbedUnimplementedLogicServiceServer() {}
func (UnimplementedLogicServiceServer) testEmbeddedByValue()                      {}

// UnsafeLogicServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LogicServiceServer will
// result in compilation errors.
type UnsafeLogicServiceServer interface {
	mustEmbedUnimplementedLogicServiceServer()
}

func RegisterLogicServiceServer(s grpc.ServiceRegistrar, srv LogicServiceServer) {
	// If the following call panics, it indicates UnimplementedLogicServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LogicService_ServiceDesc, srv)
}

func _LogicService_OnMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OnMessageReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogicServiceServer).OnMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LogicService_OnMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogicServiceServer).OnMessage(ctx, req.(*OnMessageReq))
	}
	return interceptor(ctx, in, info, handler)
}

// LogicService_ServiceDesc is the grpc.ServiceDesc for LogicService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LogicService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "danmu.LogicService",
	HandlerType: (*LogicServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "OnMessage",
			Handler:    _LogicService_OnMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/danmu.proto",
}

const (
	CometService_PushRoom_FullMethodName = "/danmu.CometService/PushRoom"
)

// CometServiceClient is the client API for CometService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// CometService: Job 把某房间的一批消息定向推给持有该房间的 Comet。
type CometServiceClient interface {
	PushRoom(ctx context.Context, in *PushRoomReq, opts ...grpc.CallOption) (*PushRoomResp, error)
}

type cometServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCometServiceClient(cc grpc.ClientConnInterface) CometServiceClient {
	return &cometServiceClient{cc}
}

func (c *cometServiceClient) PushRoom(ctx context.Context, in *PushRoomReq, opts ...grpc.CallOption) (*PushRoomResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PushRoomResp)
	err := c.cc.Invoke(ctx, CometService_PushRoom_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CometServiceServer is the server API for CometService service.
// All implementations must embed UnimplementedCometServiceServer
// for forward compatibility.
//
// CometService: Job 把某房间的一批消息定向推给持有该房间的 Comet。
type CometServiceServer interface {
	PushRoom(context.Context, *PushRoomReq) (*PushRoomResp, error)
	mustEmbedUnimplementedCometServiceServer()
}

// UnimplementedCometServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCometServiceServer struct{}

func (UnimplementedCometServiceServer) PushRoom(context.Context, *PushRoomReq) (*PushRoomResp, error) {
	return nil, status.Error(codes.Unimplemented, "method PushRoom not implemented")
}
func (UnimplementedCometServiceServer) mustEmbedUnimplementedCometServiceServer() {}
func (UnimplementedCometServiceServer) testEmbeddedByValue()                      {}

// UnsafeCometServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CometServiceServer will
// result in compilation errors.
type UnsafeCometServiceServer interface {
	mustEmbedUnimplementedCometServiceServer()
}

func RegisterCometServiceServer(s grpc.ServiceRegistrar, srv CometServiceServer) {
	// If the following call panics, it indicates UnimplementedCometServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CometService_ServiceDesc, srv)
}

func _CometService_PushRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PushRoomReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CometServiceServer).PushRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CometService_PushRoom_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CometServiceServer).PushRoom(ctx, req.(*PushRoomReq))
	}
	return interceptor(ctx, in, info, handler)
}

// CometService_ServiceDesc is the grpc.ServiceDesc for CometService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CometService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "danmu.CometService",
	HandlerType: (*CometServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PushRoom",
			Handler:    _CometService_PushRoom_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/danmu.proto",
}
