// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             (unknown)
// source: video/v1/video.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationVideoCompleteUpload = "/api.video.v1.Video/CompleteUpload"
const OperationVideoCreateVideo = "/api.video.v1.Video/CreateVideo"
const OperationVideoGetInteractStats = "/api.video.v1.Video/GetInteractStats"
const OperationVideoGetVideo = "/api.video.v1.Video/GetVideo"
const OperationVideoListComments = "/api.video.v1.Video/ListComments"
const OperationVideoListDanmu = "/api.video.v1.Video/ListDanmu"
const OperationVideoListMyVideos = "/api.video.v1.Video/ListMyVideos"
const OperationVideoListRelated = "/api.video.v1.Video/ListRelated"
const OperationVideoListVideos = "/api.video.v1.Video/ListVideos"
const OperationVideoPostComment = "/api.video.v1.Video/PostComment"
const OperationVideoPostDanmu = "/api.video.v1.Video/PostDanmu"
const OperationVideoToggleFavorite = "/api.video.v1.Video/ToggleFavorite"
const OperationVideoToggleLike = "/api.video.v1.Video/ToggleLike"

type VideoHTTPServer interface {
	CompleteUpload(context.Context, *CompleteUploadRequest) (*CompleteUploadReply, error)
	CreateVideo(context.Context, *CreateVideoRequest) (*CreateVideoReply, error)
	GetInteractStats(context.Context, *GetInteractStatsRequest) (*InteractStats, error)
	GetVideo(context.Context, *GetVideoRequest) (*VideoInfo, error)
	// ListComments ---- 互动（M5，同库；日后可拆 interact 服务）----
	ListComments(context.Context, *ListCommentsRequest) (*ListCommentsReply, error)
	// ListDanmu 点播历史弹幕（按播放进度 offset_ms 区间拉取）
	ListDanmu(context.Context, *ListDanmuRequest) (*ListDanmuReply, error)
	ListMyVideos(context.Context, *ListMyVideosRequest) (*ListVideosReply, error)
	// ListRelated 相关推荐:同分区按热度,排除自身(播放页侧栏)
	ListRelated(context.Context, *ListRelatedRequest) (*ListVideosReply, error)
	ListVideos(context.Context, *ListVideosRequest) (*ListVideosReply, error)
	PostComment(context.Context, *PostCommentRequest) (*PostCommentReply, error)
	// PostDanmu 持久化一条点播弹幕（JWT）；实时广播仍走 comet WS
	PostDanmu(context.Context, *PostDanmuRequest) (*PostDanmuReply, error)
	ToggleFavorite(context.Context, *ToggleFavoriteRequest) (*ToggleFavoriteReply, error)
	ToggleLike(context.Context, *ToggleLikeRequest) (*ToggleLikeReply, error)
}

func RegisterVideoHTTPServer(s *http.Server, srv VideoHTTPServer) {
	r := s.Route("/")
	r.POST("/v1/videos", _Video_CreateVideo0_HTTP_Handler(srv))
	r.POST("/v1/videos/{id}/complete", _Video_CompleteUpload0_HTTP_Handler(srv))
	r.GET("/v1/videos", _Video_ListVideos0_HTTP_Handler(srv))
	r.GET("/v1/videos/{id}/related", _Video_ListRelated0_HTTP_Handler(srv))
	r.GET("/v1/videos/{id}", _Video_GetVideo0_HTTP_Handler(srv))
	r.GET("/v1/me/videos", _Video_ListMyVideos0_HTTP_Handler(srv))
	r.GET("/v1/videos/{id}/danmu", _Video_ListDanmu0_HTTP_Handler(srv))
	r.POST("/v1/videos/{id}/danmu", _Video_PostDanmu0_HTTP_Handler(srv))
	r.GET("/v1/videos/{id}/comments", _Video_ListComments0_HTTP_Handler(srv))
	r.POST("/v1/videos/{id}/comments", _Video_PostComment0_HTTP_Handler(srv))
	r.POST("/v1/videos/{id}/like", _Video_ToggleLike0_HTTP_Handler(srv))
	r.POST("/v1/videos/{id}/favorite", _Video_ToggleFavorite0_HTTP_Handler(srv))
	r.GET("/v1/videos/{id}/stats", _Video_GetInteractStats0_HTTP_Handler(srv))
}

func _Video_CreateVideo0_HTTP_Handler(srv VideoHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateVideoRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationVideoCreateVideo)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateVideo(ctx, req.(*CreateVideoRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateVideoReply)
		return ctx.Result(200, reply)
	}
}

func _Video_CompleteUpload0_HTTP_Handler(srv VideoHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CompleteUploadRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationVideoCompleteUpload)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CompleteUpload(ctx, req.(*CompleteUploadRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CompleteUploadReply)
		return ctx.Result(200, reply)
	}
}

func _Video_ListVideos0_HTTP_Handler(srv VideoHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListVideosRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationVideoListVideos)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListVideos(ctx, req.(*ListVideosRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListVideosReply)
		return ctx.Result(200, reply)
	}
}

func _Video_ListRelated0_HTTP_Handler(srv VideoHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListRelatedRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationVideoListRelated)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListRelated(ctx, req.(*ListRelatedRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListVideosReply)
		return ctx.Result(200, reply)
	}
}

func _Video_GetVideo0_HTTP_Handler(srv VideoHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetVideoRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationVideoGetVideo)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetVideo(ctx, req.(*GetVideoRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*VideoInfo)
		return ctx.Result(200, reply)
	}
}

func _Video_ListMyVideos0_HTTP_Handler(srv VideoHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListMyVideosRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationVideoListMyVideos)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListMyVideos(ctx, req.(*ListMyVideosRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListVideosReply)
		return ctx.Result(200, reply)
	}
}

func _Video_ListDanmu0_HTTP_Handler(srv VideoHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListDanmuRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationVideoListDanmu)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListDanmu(ctx, req.(*ListDanmuRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListDanmuReply)
		return ctx.Result(200, reply)
	}
}

func _Video_PostDanmu0_HTTP_Handler(srv VideoHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in PostDanmuRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationVideoPostDanmu)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.PostDanmu(ctx, req.(*PostDanmuRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*PostDanmuReply)
		return ctx.Result(200, reply)
	}
}

func _Video_ListComments0_HTTP_Handler(srv VideoHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListCommentsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationVideoListComments)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListComments(ctx, req.(*ListCommentsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListCommentsReply)
		return ctx.Result(200, reply)
	}
}

func _Video_PostComment0_HTTP_Handler(srv VideoHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in PostCommentRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationVideoPostComment)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.PostComment(ctx, req.(*PostCommentRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*PostCommentReply)
		return ctx.Result(200, reply)
	}
}

func _Video_ToggleLike0_HTTP_Handler(srv VideoHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ToggleLikeRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationVideoToggleLike)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ToggleLike(ctx, req.(*ToggleLikeRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ToggleLikeReply)
		return ctx.Result(200, reply)
	}
}

func _Video_ToggleFavorite0_HTTP_Handler(srv VideoHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ToggleFavoriteRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationVideoToggleFavorite)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ToggleFavorite(ctx, req.(*ToggleFavoriteRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ToggleFavoriteReply)
		return ctx.Result(200, reply)
	}
}

func _Video_GetInteractStats0_HTTP_Handler(srv VideoHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetInteractStatsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationVideoGetInteractStats)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetInteractStats(ctx, req.(*GetInteractStatsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*InteractStats)
		return ctx.Result(200, reply)
	}
}

type VideoHTTPClient interface {
	CompleteUpload(ctx context.Context, req *CompleteUploadRequest, opts ...http.CallOption) (rsp *CompleteUploadReply, err error)
	CreateVideo(ctx context.Context, req *CreateVideoRequest, opts ...http.CallOption) (rsp *CreateVideoReply, err error)
	GetInteractStats(ctx context.Context, req *GetInteractStatsRequest, opts ...http.CallOption) (rsp *InteractStats, err error)
	GetVideo(ctx context.Context, req *GetVideoRequest, opts ...http.CallOption) (rsp *VideoInfo, err error)
	// ListComments ---- 互动（M5，同库；日后可拆 interact 服务）----
	ListComments(ctx context.Context, req *ListCommentsRequest, opts ...http.CallOption) (rsp *ListCommentsReply, err error)
	// ListDanmu 点播历史弹幕（按播放进度 offset_ms 区间拉取）
	ListDanmu(ctx context.Context, req *ListDanmuRequest, opts ...http.CallOption) (rsp *ListDanmuReply, err error)
	ListMyVideos(ctx context.Context, req *ListMyVideosRequest, opts ...http.CallOption) (rsp *ListVideosReply, err error)
	// ListRelated 相关推荐:同分区按热度,排除自身(播放页侧栏)
	ListRelated(ctx context.Context, req *ListRelatedRequest, opts ...http.CallOption) (rsp *ListVideosReply, err error)
	ListVideos(ctx context.Context, req *ListVideosRequest, opts ...http.CallOption) (rsp *ListVideosReply, err error)
	PostComment(ctx context.Context, req *PostCommentRequest, opts ...http.CallOption) (rsp *PostCommentReply, err error)
	// PostDanmu 持久化一条点播弹幕（JWT）；实时广播仍走 comet WS
	PostDanmu(ctx context.Context, req *PostDanmuRequest, opts ...http.CallOption) (rsp *PostDanmuReply, err error)
	ToggleFavorite(ctx context.Context, req *ToggleFavoriteRequest, opts ...http.CallOption) (rsp *ToggleFavoriteReply, err error)
	ToggleLike(ctx context.Context, req *ToggleLikeRequest, opts ...http.CallOption) (rsp *ToggleLikeReply, err error)
}

type VideoHTTPClientImpl struct {
	cc *http.Client
}

func NewVideoHTTPClient(client *http.Client) VideoHTTPClient {
	return &VideoHTTPClientImpl{client}
}

func (c *VideoHTTPClientImpl) CompleteUpload(ctx context.Context, in *CompleteUploadRequest, opts ...http.CallOption) (*CompleteUploadReply, error) {
	var out CompleteUploadReply
	pattern := "/v1/videos/{id}/complete"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationVideoCompleteUpload))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *VideoHTTPClientImpl) CreateVideo(ctx context.Context, in *CreateVideoRequest, opts ...http.CallOption) (*CreateVideoReply, error) {
	var out CreateVideoReply
	pattern := "/v1/videos"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationVideoCreateVideo))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *VideoHTTPClientImpl) GetInteractStats(ctx context.Context, in *GetInteractStatsRequest, opts ...http.CallOption) (*InteractStats, error) {
	var out InteractStats
	pattern := "/v1/videos/{id}/stats"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationVideoGetInteractStats))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *VideoHTTPClientImpl) GetVideo(ctx context.Context, in *GetVideoRequest, opts ...http.CallOption) (*VideoInfo, error) {
	var out VideoInfo
	pattern := "/v1/videos/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationVideoGetVideo))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListComments ---- 互动（M5，同库；日后可拆 interact 服务）----
func (c *VideoHTTPClientImpl) ListComments(ctx context.Context, in *ListCommentsRequest, opts ...http.CallOption) (*ListCommentsReply, error) {
	var out ListCommentsReply
	pattern := "/v1/videos/{id}/comments"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationVideoListComments))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListDanmu 点播历史弹幕（按播放进度 offset_ms 区间拉取）
func (c *VideoHTTPClientImpl) ListDanmu(ctx context.Context, in *ListDanmuRequest, opts ...http.CallOption) (*ListDanmuReply, error) {
	var out ListDanmuReply
	pattern := "/v1/videos/{id}/danmu"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationVideoListDanmu))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *VideoHTTPClientImpl) ListMyVideos(ctx context.Context, in *ListMyVideosRequest, opts ...http.CallOption) (*ListVideosReply, error) {
	var out ListVideosReply
	pattern := "/v1/me/videos"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationVideoListMyVideos))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListRelated 相关推荐:同分区按热度,排除自身(播放页侧栏)
func (c *VideoHTTPClientImpl) ListRelated(ctx context.Context, in *ListRelatedRequest, opts ...http.CallOption) (*ListVideosReply, error) {
	var out ListVideosReply
	pattern := "/v1/videos/{id}/related"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationVideoListRelated))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *VideoHTTPClientImpl) ListVideos(ctx context.Context, in *ListVideosRequest, opts ...http.CallOption) (*ListVideosReply, error) {
	var out ListVideosReply
	pattern := "/v1/videos"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationVideoListVideos))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *VideoHTTPClientImpl) PostComment(ctx context.Context, in *PostCommentRequest, opts ...http.CallOption) (*PostCommentReply, error) {
	var out PostCommentReply
	pattern := "/v1/videos/{id}/comments"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationVideoPostComment))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// PostDanmu 持久化一条点播弹幕（JWT）；实时广播仍走 comet WS
func (c *VideoHTTPClientImpl) PostDanmu(ctx context.Context, in *PostDanmuRequest, opts ...http.CallOption) (*PostDanmuReply, error) {
	var out PostDanmuReply
	pattern := "/v1/videos/{id}/danmu"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationVideoPostDanmu))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *VideoHTTPClientImpl) ToggleFavorite(ctx context.Context, in *ToggleFavoriteRequest, opts ...http.CallOption) (*ToggleFavoriteReply, error) {
	var out ToggleFavoriteReply
	pattern := "/v1/videos/{id}/favorite"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationVideoToggleFavorite))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *VideoHTTPClientImpl) ToggleLike(ctx context.Context, in *ToggleLikeRequest, opts ...http.CallOption) (*ToggleLikeReply, error) {
	var out ToggleLikeReply
	pattern := "/v1/videos/{id}/like"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationVideoToggleLike))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
